# Transformers for Data Flow Graphs

In [1]:
import copy
import time
import math
import random
from typing import Tuple

import torch
from torch import nn, Tensor
import torch.nn.functional as F
from torch.nn import TransformerEncoder, TransformerEncoderLayer
from torch.utils.data import dataset
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from datasets import load_dataset

/home/jachym/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
class PositionalEncoding(nn.Module):

    def __init__(self, d_model: int, dropout: float = 0.1, max_len: int = 5000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        position = torch.arange(max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe = torch.zeros(max_len, 1, d_model)
        pe[:, 0, 0::2] = torch.sin(position * div_term)
        pe[:, 0, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: Tensor, shape [seq_len, batch_size, embedding_dim]
        """
        x = x + self.pe[:x.size(0)]
        return self.dropout(x)

In [6]:
class TransformerModel(nn.Module):

    def __init__(self, ntoken: int, d_model: int, nhead: int, d_hid: int,
                 nlayers: int, dropout: float = 0.5):
        super().__init__()
        self.model_type = 'Transformer'
        self.pos_encoder = PositionalEncoding(d_model, dropout)
        encoder_layers = TransformerEncoderLayer(d_model, nhead, d_hid, dropout)
        self.transformer_encoder = TransformerEncoder(encoder_layers, nlayers)
        self.encoder = nn.Embedding(ntoken, d_model)
        self.d_model = d_model
        self.decoder = nn.Linear(d_model, ntoken)

        self.init_weights()

    def init_weights(self) -> None:
        initrange = 0.1
        self.encoder.weight.data.uniform_(-initrange, initrange)
        self.decoder.bias.data.zero_()
        self.decoder.weight.data.uniform_(-initrange, initrange)

    def forward(self, src: Tensor, src_mask: Tensor) -> Tensor:
        """
        Args:
            src: Tensor, shape [seq_len, batch_size]
            src_mask: Tensor, shape [seq_len, seq_len]

        Returns:
            output Tensor of shape [seq_len, batch_size, ntoken]
        """
        src = self.encoder(src) * math.sqrt(self.d_model)
        src = self.pos_encoder(src)
        output = self.transformer_encoder(src, src_mask)
        output = self.decoder(output)
        return output


def generate_square_subsequent_mask(sz: int) -> Tensor:
    """Generates an upper-triangular matrix of -inf, with zeros on diag."""
    return torch.triu(torch.ones(sz, sz) * float('-inf'), diagonal=1)

In [ ]:
def split_data(data):
    train = []
    val = []
    test = []

    for el in data:
        pos = random.randrange(100)
        if (pos < 15):
            test.append(el)
        elif (pos >= 15 and pos < 30):
            val.append(el)
        else:
            train.append(el)
    return train, val, test

def data_process(raw_text_iter: dataset.IterableDataset) -> Tensor:
    """Converts raw text into a flat Tensor."""
    data = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in raw_text_iter]
    return torch.cat(tuple(filter(lambda t: t.numel() > 0, data)))

def batchify(data: Tensor, bsz: int) -> Tensor:
    """Divides the data into bsz separate sequences, removing extra elements
    that wouldn't cleanly fit.

    Args:
        data: Tensor, shape [N]
        bsz: int, batch size

    Returns:
        Tensor of shape [N // bsz, bsz]
    """
    seq_len = data.size(0) // bsz
    data = data[:seq_len * bsz]
    data = data.view(bsz, seq_len).t().contiguous()
    return data.to(device)

def get_batch(source: Tensor, i: int) -> Tuple[Tensor, Tensor]:
    """
    Args:
        source: Tensor, shape [full_seq_len, batch_size]
        i: int

    Returns:
        tuple (data, target), where data has shape [seq_len, batch_size] and
        target has shape [seq_len * batch_size]
    """
    seq_len = min(bptt, len(source) - 1 - i)
    data = source[i:i+seq_len]
    target = source[i+1:i+1+seq_len].reshape(-1)
    return data, target

In [20]:
def train(model: nn.Module) -> None:
    model.train()  # turn on train mode
    total_loss = 0.
    log_interval = 200
    start_time = time.time()
    src_mask = generate_square_subsequent_mask(bptt).to(device)

    num_batches = len(train_data) // bptt
    for batch, i in enumerate(range(0, train_data.size(0) - 1, bptt)):
        data, targets = get_batch(train_data, i)
        seq_len = data.size(0)
        if seq_len != bptt:  # only on last batch
            src_mask = src_mask[:seq_len, :seq_len]
        output = model(data, src_mask)
        loss = criterion(output.view(-1, ntokens), targets)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)
        optimizer.step()

        total_loss += loss.item()
        if batch % log_interval == 0 and batch > 0:
            lr = scheduler.get_last_lr()[0]
            ms_per_batch = (time.time() - start_time) * 1000 / log_interval
            cur_loss = total_loss / log_interval
            ppl = math.exp(cur_loss)
            print(f'| epoch {epoch:3d} | {batch:5d}/{num_batches:5d} batches | '
                  f'lr {lr:02.2f} | ms/batch {ms_per_batch:5.2f} | '
                  f'loss {cur_loss:5.2f} | ppl {ppl:8.2f}')
            total_loss = 0
            start_time = time.time()

def evaluate(model: nn.Module, eval_data: Tensor) -> float:
    model.eval()  # turn on evaluation mode
    total_loss = 0.
    src_mask = generate_square_subsequent_mask(bptt).to(device)
    with torch.no_grad():
        for i in range(0, eval_data.size(0) - 1, bptt):
            data, targets = get_batch(eval_data, i)
            print("Data is:")
            print(data)
            print("Targets are:")
            print(targets)
            seq_len = data.size(0)
            if seq_len != bptt:
                src_mask = src_mask[:seq_len, :seq_len]
            output = model(data, src_mask)
            output_flat = output.view(-1, ntokens)
            total_loss += seq_len * criterion(output_flat, targets).item()
    return total_loss / (len(eval_data) - 1)

### Preprocessing data

1. Load data
2. Apply tokenizer
3. Build a vocabulary
4. Convert to a tensor
5. Put the data into batches

In [21]:
DATA_LOCATION = './data/data3node.txt'
train_iter = open(DATA_LOCATION, 'r').read().splitlines()
tokenizer = get_tokenizer(None)
batch_size = 20
eval_batch_size = 4

vocab = build_vocab_from_iterator(map(tokenizer,train_iter))

train_i, val_i, test_i = split_data(train_iter)
train_data = data_process(train_i)
val_data = data_process(val_i)
test_data = data_process(test_i)


train_data = batchify(train_data, batch_size)  # shape [seq_len, batch_size]
val_data = batchify(val_data, eval_batch_size)
test_data = batchify(test_data, eval_batch_size)

In [22]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

bptt = 4

ntokens = len(vocab)  # size of vocabulary
emsize = 200  # embedding dimension
d_hid = 200  # dimension of the feedforward network model in nn.TransformerEncoder
nlayers = 2  # number of nn.TransformerEncoderLayer in nn.TransformerEncoder
nhead = 2  # number of heads in nn.MultiheadAttention
dropout = 0.2  # dropout probability
model = TransformerModel(ntokens, emsize, nhead, d_hid, nlayers, dropout).to(device)

criterion = nn.CrossEntropyLoss()
lr = 5.0  # learning rate
optimizer = torch.optim.SGD(model.parameters(), lr=lr)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1.0, gamma=0.95)

best_val_loss = float('inf')
epochs = 3
best_model = None

for epoch in range(1, epochs + 1):
    epoch_start_time = time.time()
    train(model)
    val_loss = evaluate(model, val_data)
    val_ppl = math.exp(val_loss)
    elapsed = time.time() - epoch_start_time
    print('-' * 89)
    print(f'| end of epoch {epoch:3d} | time: {elapsed:5.2f}s | '
          f'valid loss {val_loss:5.2f} | valid ppl {val_ppl:8.2f}')
    print('-' * 89)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model = copy.deepcopy(model)

    scheduler.step()

test_loss = evaluate(best_model, test_data)
test_ppl = math.exp(test_loss)
print('=' * 89)
print(f'| End of training | test loss {test_loss:5.2f} | '
      f'test ppl {test_ppl:8.2f}')
print('=' * 89)

| epoch   1 |   200/ 1505 batches | lr 5.00 | ms/batch 27.65 | loss  5.46 | ppl   236.00
| epoch   1 |   400/ 1505 batches | lr 5.00 | ms/batch 27.00 | loss  6.15 | ppl   468.37
| epoch   1 |   600/ 1505 batches | lr 5.00 | ms/batch 26.30 | loss  6.11 | ppl   450.91
| epoch   1 |   800/ 1505 batches | lr 5.00 | ms/batch 28.40 | loss  6.12 | ppl   455.85
| epoch   1 |  1000/ 1505 batches | lr 5.00 | ms/batch 26.64 | loss  5.97 | ppl   390.45
| epoch   1 |  1200/ 1505 batches | lr 5.00 | ms/batch 28.77 | loss  6.00 | ppl   403.88
| epoch   1 |  1400/ 1505 batches | lr 5.00 | ms/batch 39.02 | loss  5.85 | ppl   346.54
Data is:
tensor([[7607, 3156,  255, 1390],
        [8047, 3156,  255, 1390],
        [7607, 3156,  256, 1390],
        [  21, 3157,  256, 1392]])
Targets are:
tensor([8047, 3156,  255, 1390, 7607, 3156,  256, 1390,   21, 3157,  256, 1392,
        4092, 3157,  256, 1392])
Data is:
tensor([[4092, 3157,  256, 1392],
        [  27, 3157,  257, 1393],
        [4092, 3157,  257, 1

Data is:
tensor([[4192, 7908,  329, 5156],
        [   5, 7908,  329, 5156],
        [ 190, 7908,  333, 5156],
        [  11, 7908,  333, 1443]])
Targets are:
tensor([   5, 7908,  329, 5156,  190, 7908,  333, 5156,   11, 7908,  333, 1443,
         190, 7909,  333, 1443])
Data is:
tensor([[ 190, 7909,  333, 1443],
        [  11, 7909,  333, 1443],
        [ 190, 3013,  334, 1443],
        [   0, 3013,  334, 5157]])
Targets are:
tensor([  11, 7909,  333, 1443,  190, 3013,  334, 1443,    0, 3013,  334, 5157,
        4185, 3013,  334, 5157])
Data is:
tensor([[4185, 3013,  334, 5157],
        [   1, 3013,  334, 5157],
        [4185, 3013,  335, 5158],
        [   4, 3013,  335, 5158]])
Targets are:
tensor([   1, 3013,  334, 5157, 4185, 3013,  335, 5158,    4, 3013,  335, 5158,
        4185, 3013, 4308, 1445])
Data is:
tensor([[4185, 3013, 4308, 1445],
        [  17, 7910, 4308, 1445],
        [4185, 7910, 4308, 1445],
        [   9, 3014, 4308, 5159]])
Targets are:
tensor([  17, 7910, 4308,

tensor([[4216, 6905,  381, 1664],
        [   4, 6906,  486, 1664],
        [4216, 6906,  486, 1664],
        [  21, 6906, 4393, 1664]])
Targets are:
tensor([   4, 6906,  486, 1664, 4216, 6906,  486, 1664,   21, 6906, 4393, 1664,
        4216, 6906, 4393, 1665])
Data is:
tensor([[4216, 6906, 4393, 1665],
        [  11, 6906,  494, 1665],
        [4217, 6906,  494, 1665],
        [  11, 3060,  494, 1666]])
Targets are:
tensor([  11, 6906,  494, 1665, 4217, 6906,  494, 1665,   11, 3060,  494, 1666,
        4217, 3060, 4394, 1666])
Data is:
tensor([[4217, 3060, 4394, 1666],
        [   4, 3060, 4394, 1666],
        [4217, 3060, 4394, 1666],
        [  16, 3060,  495, 1666]])
Targets are:
tensor([   4, 3060, 4394, 1666, 4217, 3060, 4394, 1666,   16, 3060,  495, 1666,
        4217, 3061,  495, 1667])
Data is:
tensor([[4217, 3061,  495, 1667],
        [  16, 3061,  495, 1667],
        [4217, 3061,  495, 1668],
        [   4, 3061, 7659, 1668]])
Targets are:
tensor([  16, 3061,  495, 1667, 42

Data is:
tensor([[ 225, 3196,  645, 5422],
        [  13, 3197, 7674, 5422],
        [ 225, 3197, 7674, 5423],
        [   8, 3197, 7675, 5423]])
Targets are:
tensor([  13, 3197, 7674, 5422,  225, 3197, 7674, 5423,    8, 3197, 7675, 5423,
         226, 3198, 7675, 5423])
Data is:
tensor([[ 226, 3198, 7675, 5423],
        [   7, 3198, 7676, 5423],
        [ 226, 3198, 7676, 5424],
        [   9, 3198, 7676, 5424]])
Targets are:
tensor([   7, 3198, 7676, 5423,  226, 3198, 7676, 5424,    9, 3198, 7676, 5424,
         226, 3198,  658, 5424])
Data is:
tensor([[ 226, 3198,  658, 5424],
        [  10, 3199,  658, 5425],
        [ 226, 3199,  658, 5425],
        [   0, 3199,  658, 5425]])
Targets are:
tensor([  10, 3199,  658, 5425,  226, 3199,  658, 5425,    0, 3199,  658, 5425,
         227, 3199,  659, 5426])
Data is:
tensor([[ 227, 3199,  659, 5426],
        [   1, 3200,  659, 5426],
        [ 227, 3200,  659, 5427],
        [   3, 3200, 7677, 5427]])
Targets are:
tensor([   1, 3200,  659,

tensor([   9, 3398,  503, 1623,   60, 3398,  503, 1623,    8, 3398,  503, 5292,
          60, 3399,  511, 5292])
Data is:
tensor([[  60, 3399,  511, 5292],
        [  35, 3399,  511, 5292],
        [  60, 7131, 4407, 1625],
        [   4, 7132, 4407, 1625]])
Targets are:
tensor([  35, 3399,  511, 5292,   60, 7131, 4407, 1625,    4, 7132, 4407, 1625,
          60, 7132, 4407, 1625])
Data is:
tensor([[  60, 7132, 4407, 1625],
        [  30, 7132, 4407, 1625],
        [  60, 7133,  519, 5293],
        [   4, 7133,  519, 5294]])
Targets are:
tensor([  30, 7132, 4407, 1625,   60, 7133,  519, 5293,    4, 7133,  519, 5294,
        4107, 7133,  519, 5294])
Data is:
tensor([[4107, 7133,  519, 5294],
        [  19, 7943,  519, 5294],
        [4107, 7135,  519, 5295],
        [   2, 7136, 4408, 5295]])
Targets are:
tensor([  19, 7943,  519, 5294, 4107, 7135,  519, 5295,    2, 7136, 4408, 5295,
        4107, 3411, 4408, 5295])
Data is:
tensor([[4107, 3411, 4408, 5295],
        [  26, 3412, 4408, 5

Data is:
tensor([[  86, 3232,  565, 5384],
        [  14, 3232,  565, 5384],
        [  87, 3232,  565, 5384],
        [  25, 3233,  565, 5366]])
Targets are:
tensor([  14, 3232,  565, 5384,   87, 3232,  565, 5384,   25, 3233,  565, 5366,
          87, 3233,  566, 5367])
Data is:
tensor([[  87, 3233,  566, 5367],
        [  23, 3233,  566, 5367],
        [  87, 3233,  567, 5367],
        [  26, 3234,  567, 5368]])
Targets are:
tensor([  23, 3233,  566, 5367,   87, 3233,  567, 5367,   26, 3234,  567, 5368,
          87, 3234,  567, 5368])
Data is:
tensor([[  87, 3234,  567, 5368],
        [  13, 3234, 4459, 5368],
        [  87, 3234, 4459, 5368],
        [8040, 3234, 4459, 5368]])
Targets are:
tensor([  13, 3234, 4459, 5368,   87, 3234, 4459, 5368, 8040, 3234, 4459, 5368,
          87, 3234,  568, 5369])
Data is:
tensor([[  87, 3234,  568, 5369],
        [  33, 3235,  568, 5369],
        [4118, 3236,  568, 5369],
        [  13, 3236, 4460, 5370]])
Targets are:
tensor([  33, 3235,  568,

Data is:
tensor([[ 119, 3305,  698, 5629],
        [   4, 7055,  698, 5629],
        [ 119, 7055,  699, 5629],
        [   1, 7056,  699, 7782]])
Targets are:
tensor([   4, 7055,  698, 5629,  119, 7055,  699, 5629,    1, 7056,  699, 7782,
         119, 7056,  699, 7782])
Data is:
tensor([[ 119, 7056,  699, 7782],
        [   6, 7056,  699, 7782],
        [ 120, 7057,  699, 7782],
        [  18, 7057, 4556, 5630]])
Targets are:
tensor([   6, 7056,  699, 7782,  120, 7057,  699, 7782,   18, 7057, 4556, 5630,
         120, 7058, 4556, 5630])
Data is:
tensor([[ 120, 7058, 4556, 5630],
        [  18, 7058, 4556, 5630],
        [ 120, 7058, 4556, 5631],
        [   6, 3306,  700, 5631]])
Targets are:
tensor([  18, 7058, 4556, 5630,  120, 7058, 4556, 5631,    6, 3306,  700, 5631,
         120, 3306,  700, 5631])
Data is:
tensor([[ 120, 3306,  700, 5631],
        [   6, 3306,  700, 5631],
        [ 120, 3306,  700, 5632],
        [  37, 3306,  700, 5632]])
Targets are:
tensor([   6, 3306,  700,

tensor([  25, 7152,  869, 1744,  139, 7152,  869, 5454,   23, 7152,  869, 5454,
         140, 3441,  870, 5454])
Data is:
tensor([[ 140, 3441,  870, 5454],
        [  10, 3441,  870, 5454],
        [ 140, 3441,  871, 5455],
        [   3, 3441,  871, 5455]])
Targets are:
tensor([  10, 3441,  870, 5454,  140, 3441,  871, 5455,    3, 3441,  871, 5455,
         141, 3441,  871, 5455])
Data is:
tensor([[ 141, 3441,  871, 5455],
        [  13, 7153,  858, 5455],
        [ 141, 7153,  858, 5455],
        [8045, 7153,  858, 5456]])
Targets are:
tensor([  13, 7153,  858, 5455,  141, 7153,  858, 5455, 8045, 7153,  858, 5456,
         141, 7153,  858, 5456])
Data is:
tensor([[ 141, 7153,  858, 5456],
        [   3, 3442,  859, 5456],
        [ 142, 3442,  859, 1739],
        [   3, 3442,  859, 1739]])
Targets are:
tensor([   3, 3442,  859, 5456,  142, 3442,  859, 1739,    3, 3442,  859, 1739,
         142, 3442,  860, 1739])
Data is:
tensor([[ 142, 3442,  860, 1739],
        [  14, 7154,  860, 1

Data is:
tensor([[2180, 7284, 4562, 1772],
        [2180, 7284, 4562, 5521],
        [2180, 3614, 4562, 5521],
        [2181, 3614,  714, 1773]])
Targets are:
tensor([2180, 7284, 4562, 5521, 2180, 3614, 4562, 5521, 2181, 3614,  714, 1773,
        2181, 3614,  714, 1773])
Data is:
tensor([[2181, 3614,  714, 1773],
        [2182, 3615, 4563, 1773],
        [2182, 3615, 4563, 1773],
        [2182, 3615, 4563, 1773]])
Targets are:
tensor([2182, 3615, 4563, 1773, 2182, 3615, 4563, 1773, 2182, 3615, 4563, 1773,
        2182, 3615, 4564, 5511])
Data is:
tensor([[2182, 3615, 4564, 5511],
        [6227, 3615, 4564, 5511],
        [6227, 3615, 4564, 5511],
        [6227, 3616, 4564, 1769]])
Targets are:
tensor([6227, 3615, 4564, 5511, 6227, 3615, 4564, 5511, 6227, 3616, 4564, 1769,
        6227, 3616, 4564, 1769])
Data is:
tensor([[6227, 3616, 4564, 1769],
        [6233, 3616, 4564, 5512],
        [6233, 3616, 4566, 5512],
        [6233, 3617, 4566, 5512]])
Targets are:
tensor([6233, 3616, 4564,

tensor([[6281, 7160, 4595, 1791],
        [6281, 7161, 4596, 5573],
        [6281, 7161, 4596, 5573],
        [6284, 7161, 4596, 1783]])
Targets are:
tensor([6281, 7161, 4596, 5573, 6281, 7161, 4596, 5573, 6284, 7161, 4596, 1783,
        6284, 3454, 4597, 1783])
Data is:
tensor([[6284, 3454, 4597, 1783],
        [6284, 3454, 4597, 5574],
        [6284, 3454, 4597, 5574],
        [6284, 3454, 4598, 5574]])
Targets are:
tensor([6284, 3454, 4597, 5574, 6284, 3454, 4597, 5574, 6284, 3454, 4598, 5574,
        6285, 3454, 4598, 1784])
Data is:
tensor([[6285, 3454, 4598, 1784],
        [6285, 3454, 4598, 1784],
        [6286, 3454, 4599, 1784],
        [6286, 7163, 4600, 5575]])
Targets are:
tensor([6285, 3454, 4598, 1784, 6286, 3454, 4599, 1784, 6286, 7163, 4600, 5575,
        6286, 7163, 4600, 5575])
Data is:
tensor([[6286, 7163, 4600, 5575],
        [6287, 7163, 4600, 5575],
        [6287, 3465, 4600, 1785],
        [6288, 3465,  768, 5576]])
Targets are:
tensor([6287, 7163, 4600, 5575, 62

Data is:
tensor([[6184, 3526,  831, 5859],
        [2195, 3526,  832, 5859],
        [2195, 3527,  832, 5859],
        [2196, 3528,  833, 5859]])
Targets are:
tensor([2195, 3526,  832, 5859, 2195, 3527,  832, 5859, 2196, 3528,  833, 5859,
        2196, 3528,  833, 5861])
Data is:
tensor([[2196, 3528,  833, 5861],
        [2196, 3529, 4670, 5861],
        [2196, 3518, 4670, 5861],
        [2196, 7202, 4670, 5861]])
Targets are:
tensor([2196, 3529, 4670, 5861, 2196, 3518, 4670, 5861, 2196, 7202, 4670, 5861,
        2196, 7202, 4670, 5862])
Data is:
tensor([[2196, 7202, 4670, 5862],
        [2197, 7202, 4671, 5862],
        [2197, 3519, 4671, 5862],
        [2197, 7203, 4671, 5863]])
Targets are:
tensor([2197, 7202, 4671, 5862, 2197, 3519, 4671, 5862, 2197, 7203, 4671, 5863,
        2197, 7203, 4671, 1983])
Data is:
tensor([[2197, 7203, 4671, 1983],
        [2197, 7203, 4671, 1983],
        [2198, 7203, 4672, 1983],
        [2198, 7203,  826, 1987]])
Targets are:
tensor([2197, 7203, 4671,

Data is:
tensor([[2261, 7967, 1067, 1889],
        [2261, 3656, 1067, 1889],
        [2262, 3656, 4852, 1889],
        [2262, 3656, 4852, 5696]])
Targets are:
tensor([2261, 3656, 1067, 1889, 2262, 3656, 4852, 1889, 2262, 3656, 4852, 5696,
        2262, 3657, 1068, 5696])
Data is:
tensor([[2262, 3657, 1068, 5696],
        [2262, 3657, 1068, 5696],
        [2262, 3657, 1069, 5696],
        [7811, 3658, 1069, 5697]])
Targets are:
tensor([2262, 3657, 1068, 5696, 2262, 3657, 1069, 5696, 7811, 3658, 1069, 5697,
        6207, 3658, 1069, 5697])
Data is:
tensor([[6207, 3658, 1069, 5697],
        [6207, 3658, 1069, 5697],
        [6207, 7968, 4853, 5697],
        [6208, 3659, 4853, 5698]])
Targets are:
tensor([6207, 3658, 1069, 5697, 6207, 7968, 4853, 5697, 6208, 3659, 4853, 5698,
        6208, 3659, 4853, 5698])
Data is:
tensor([[6208, 3659, 4853, 5698],
        [6208, 3659, 4853, 5698],
        [6208, 3660, 4853, 5698],
        [6208, 3660, 4853, 5698]])
Targets are:
tensor([6208, 3659, 4853,

Data is:
tensor([[6562, 3817, 1121, 5747],
        [6562, 3818, 4882, 5747],
        [2548, 3819, 4882, 5747],
        [2548, 3819, 1122, 5747]])
Targets are:
tensor([6562, 3818, 4882, 5747, 2548, 3819, 4882, 5747, 2548, 3819, 1122, 5747,
        2549, 7430, 1122, 5747])
Data is:
tensor([[2549, 7430, 1122, 5747],
        [2549, 7431, 1122, 5748],
        [2549, 7431, 1122, 5748],
        [2549, 7432, 1122, 5748]])
Targets are:
tensor([2549, 7431, 1122, 5748, 2549, 7431, 1122, 5748, 2549, 7432, 1122, 5748,
        6564, 7432, 1122, 5748])
Data is:
tensor([[6564, 7432, 1122, 5748],
        [6564, 7432, 1123, 1916],
        [6564, 8004, 1123, 1916],
        [2550, 8004, 1124, 1916]])
Targets are:
tensor([6564, 7432, 1123, 1916, 6564, 8004, 1123, 1916, 2550, 8004, 1124, 1916,
        2550, 7433, 1124, 1918])
Data is:
tensor([[2550, 7433, 1124, 1918],
        [6565, 7433, 4883, 1918],
        [6565, 3832, 4883, 1919],
        [6565, 3832, 4883, 1919]])
Targets are:
tensor([6565, 7433, 4883,

Data is:
tensor([[6674, 7971, 7704, 5807],
        [2718, 7971, 7704, 5807],
        [2718, 3663, 7704, 5808],
        [2718, 3663, 7704, 5808]])
Targets are:
tensor([2718, 7971, 7704, 5807, 2718, 3663, 7704, 5808, 2718, 3663, 7704, 5808,
        2718, 3663, 4745, 5808])
Data is:
tensor([[2718, 3663, 4745, 5808],
        [2718, 3663, 4745, 5808],
        [2718, 3666, 4745, 5808],
        [6675, 3666,  979, 5809]])
Targets are:
tensor([2718, 3663, 4745, 5808, 2718, 3666, 4745, 5808, 6675, 3666,  979, 5809,
        6675, 3667,  979, 5809])
Data is:
tensor([[6675, 3667,  979, 5809],
        [6675, 3667,  979, 5820],
        [6675, 3668,  979, 5820],
        [2719, 3668,  979, 5820]])
Targets are:
tensor([6675, 3667,  979, 5820, 6675, 3668,  979, 5820, 2719, 3668,  979, 5820,
        2719, 7321,  979, 5822])
Data is:
tensor([[2719, 7321,  979, 5822],
        [2719, 7321,  979, 5822],
        [6676, 7321,  982, 5822],
        [6676, 7321,  983, 5822]])
Targets are:
tensor([2719, 7321,  979,

Data is:
tensor([[2747, 3713, 4791, 2125],
        [2747, 3714, 4791, 6096],
        [2748, 3714, 4791, 6096],
        [2749, 7340, 1012, 6096]])
Targets are:
tensor([2747, 3714, 4791, 6096, 2748, 3714, 4791, 6096, 2749, 7340, 1012, 6096,
        2749, 7340, 1012, 6096])
Data is:
tensor([[2749, 7340, 1012, 6096],
        [2750, 7340, 1012, 6096],
        [2750, 3715, 1012, 6096],
        [2750, 3715, 1015, 6096]])
Targets are:
tensor([2750, 7340, 1012, 6096, 2750, 3715, 1012, 6096, 2750, 3715, 1015, 6096,
        2750, 3715, 1016, 2117])
Data is:
tensor([[2750, 3715, 1016, 2117],
        [2750, 3715, 1016, 2117],
        [2752, 3715, 1016, 2117],
        [2752, 7341, 4804, 2117]])
Targets are:
tensor([2750, 3715, 1016, 2117, 2752, 3715, 1016, 2117, 2752, 7341, 4804, 2117,
        2752, 7341, 4804, 2117])
Data is:
tensor([[2752, 7341, 4804, 2117],
        [2752, 7341, 4804, 7790],
        [2752, 7342, 4805, 2118],
        [6709, 7343, 4805, 2118]])
Targets are:
tensor([2752, 7341, 4804,

tensor([[2586, 3769, 1224, 6131],
        [2586, 3769, 1225, 6132],
        [2586, 3770, 1225, 6132],
        [2586, 3771, 1226, 6132]])
Targets are:
tensor([2586, 3769, 1225, 6132, 2586, 3770, 1225, 6132, 2586, 3771, 1226, 6132,
        2586, 3771, 1226, 6132])
Data is:
tensor([[2586, 3771, 1226, 6132],
        [2586, 3771, 5011, 6132],
        [6589, 3771, 5011, 6133],
        [6589, 3771, 5011, 6133]])
Targets are:
tensor([2586, 3771, 5011, 6132, 6589, 3771, 5011, 6133, 6589, 3771, 5011, 6133,
        2587, 3771, 5011, 6133])
Data is:
tensor([[2587, 3771, 5011, 6133],
        [2588, 3772, 1227, 6133],
        [2588, 3772, 1227, 2164],
        [2588, 3772, 1227, 2164]])
Targets are:
tensor([2588, 3772, 1227, 6133, 2588, 3772, 1227, 2164, 2588, 3772, 1227, 2164,
        2588, 3772, 1227, 2164])
Data is:
tensor([[2588, 3772, 1227, 2164],
        [2589, 3773, 1228, 2165],
        [2589, 3773, 1228, 2165],
        [6590, 3773, 1228, 2165]])
Targets are:
tensor([2589, 3773, 1228, 2165, 25

Data is:
tensor([[2658, 7564, 5050, 2067],
        [2658, 4005, 5050, 5943],
        [2658, 4005, 5050, 5943],
        [2659, 4005, 5050, 5944]])
Targets are:
tensor([2658, 4005, 5050, 5943, 2658, 4005, 5050, 5943, 2659, 4005, 5050, 5944,
        2659, 7565, 5051, 5944])
Data is:
tensor([[2659, 7565, 5051, 5944],
        [2660, 7565, 5051, 5944],
        [2660, 7565, 5051, 5944],
        [2660, 4006, 1282, 5946]])
Targets are:
tensor([2660, 7565, 5051, 5944, 2660, 7565, 5051, 5944, 2660, 4006, 1282, 5946,
        2661, 7566, 1282, 5947])
Data is:
tensor([[2661, 7566, 1282, 5947],
        [2661, 4007, 1282, 5947],
        [2661, 7567, 5052, 5948],
        [2662, 7567, 5052, 5948]])
Targets are:
tensor([2661, 4007, 1282, 5947, 2661, 7567, 5052, 5948, 2662, 7567, 5052, 5948,
        2663, 7567, 5052, 5949])
Data is:
tensor([[2663, 7567, 5052, 5949],
        [2649, 7567, 5052, 5949],
        [2649, 7567, 5052, 5949],
        [2649, 4008, 5052, 5950]])
Targets are:
tensor([2649, 7567, 5052,

Data is:
tensor([[2913, 7604, 4905, 6020],
        [2913, 7604, 4905, 6020],
        [2913, 7604, 1154, 6020],
        [2914, 7604, 1154, 2092]])
Targets are:
tensor([2913, 7604, 4905, 6020, 2913, 7604, 1154, 6020, 2914, 7604, 1154, 2092,
        2914, 7604, 1154, 2092])
Data is:
tensor([[2914, 7604, 1154, 2092],
        [2915, 4083, 1154, 2092],
        [2915, 4083, 1154, 2092],
        [2915, 4083, 1154, 2092]])
Targets are:
tensor([2915, 4083, 1154, 2092, 2915, 4083, 1154, 2092, 2915, 4083, 1154, 2092,
        2915, 4083, 1154, 6021])
Data is:
tensor([[2915, 4083, 1154, 6021],
        [2917, 7605, 4906, 6021],
        [2917, 4084, 4906, 6021],
        [2917, 4084, 4906, 6021]])
Targets are:
tensor([2917, 7605, 4906, 6021, 2917, 4084, 4906, 6021, 2917, 4084, 4906, 6021,
        2917, 7606, 4906, 6021])
Data is:
tensor([[2917, 7606, 4906, 6021],
        [6810, 7606, 4907, 6021],
        [6810, 7606, 4907, 6021],
        [6810, 4085, 4908, 6022]])
Targets are:
tensor([6810, 7606, 4907,

Data is:
tensor([[7898, 7484, 4958, 6483],
        [7898, 7484, 4958, 6483],
        [6860, 7484, 4958, 6483],
        [2971, 7484, 1211, 6484]])
Targets are:
tensor([7898, 7484, 4958, 6483, 6860, 7484, 4958, 6483, 2971, 7484, 1211, 6484,
        2971, 3923, 1211, 6485])
Data is:
tensor([[2971, 3923, 1211, 6485],
        [7899, 3923, 1213, 6485],
        [7899, 3923, 4972, 6486],
        [7899, 3923, 4972, 6486]])
Targets are:
tensor([7899, 3923, 1213, 6485, 7899, 3923, 4972, 6486, 7899, 3923, 4972, 6486,
        7899, 3923, 4973, 6486])
Data is:
tensor([[7899, 3923, 4973, 6486],
        [6861, 3923, 4973, 2444],
        [6861, 3927, 4973, 2444],
        [6861, 3927, 4973, 2466]])
Targets are:
tensor([6861, 3923, 4973, 2444, 6861, 3927, 4973, 2444, 6861, 3927, 4973, 2466,
        6861, 3928, 4974, 2466])
Data is:
tensor([[6861, 3928, 4974, 2466],
        [2960, 3928, 4974, 2466],
        [2960, 3928, 4975, 2470],
        [2960, 3929, 4975, 2470]])
Targets are:
tensor([2960, 3928, 4974,

Data is:
tensor([[2818, 8024, 1466, 2525],
        [2819, 8024, 1466, 6535],
        [2819, 3982, 1451, 6535],
        [2819, 3982, 1451, 6535]])
Targets are:
tensor([2819, 8024, 1466, 6535, 2819, 3982, 1451, 6535, 2819, 3982, 1451, 6535,
        2820, 3982, 1452, 6535])
Data is:
tensor([[2820, 3982, 1452, 6535],
        [2820, 3982, 1452, 6535],
        [2820, 3982, 1453, 6536],
        [2820, 3982, 1453, 6536]])
Targets are:
tensor([2820, 3982, 1452, 6535, 2820, 3982, 1453, 6536, 2820, 3982, 1453, 6536,
        7873, 3982, 1453, 6536])
Data is:
tensor([[7873, 3982, 1453, 6536],
        [2821, 3982, 1453, 6536],
        [2821, 7544, 1453, 6536],
        [2821, 7544, 1454, 6537]])
Targets are:
tensor([2821, 3982, 1453, 6536, 2821, 7544, 1453, 6536, 2821, 7544, 1454, 6537,
        2822, 7544, 1454, 6537])
Data is:
tensor([[2822, 7544, 1454, 6537],
        [2822, 7544, 1454, 6537],
        [2822, 7545, 1455, 6537],
        [2822, 7545, 1455, 6537]])
Targets are:
tensor([2822, 7544, 1454,

Data is:
tensor([[6776, 4365, 1538, 2424],
        [6777, 4366, 1538, 6361],
        [6777, 4366, 1538, 6361],
        [6777, 4366, 7744, 6362]])
Targets are:
tensor([6777, 4366, 1538, 6361, 6777, 4366, 1538, 6361, 6777, 4366, 7744, 6362,
        6777, 4366, 7744, 6362])
Data is:
tensor([[6777, 4366, 7744, 6362],
        [6777, 4367, 1539, 6362],
        [6778, 4367, 1539, 6362],
        [6779, 4367, 1539, 6362]])
Targets are:
tensor([6777, 4367, 1539, 6362, 6778, 4367, 1539, 6362, 6779, 4367, 1539, 6362,
        6779, 4367, 1540, 6363])
Data is:
tensor([[6779, 4367, 1540, 6363],
        [6779,  414, 1540, 6363],
        [2882,  414, 1540, 6363],
        [2882,  414, 1541, 6364]])
Targets are:
tensor([6779,  414, 1540, 6363, 2882,  414, 1540, 6363, 2882,  414, 1541, 6364,
        6780, 7647, 1541, 6364])
Data is:
tensor([[6780, 7647, 1541, 6364],
        [6780, 7647, 1542, 6364],
        [2896,  415, 1542, 6364],
        [2901,  415, 1542, 6366]])
Targets are:
tensor([6780, 7647, 1542,

Data is:
tensor([[3150,  480, 5099, 6463],
        [3150,  480, 5099, 6464],
        [3150,  481, 5099, 6464],
        [3150,  482, 5099, 6464]])
Targets are:
tensor([3150,  480, 5099, 6464, 3150,  481, 5099, 6464, 3150,  482, 5099, 6464,
        6980,  482, 1366, 6464])
Data is:
tensor([[6980,  482, 1366, 6464],
        [3151,  482, 1366, 6464],
        [3151,  482, 1366, 6465],
        [6973,  483, 1366, 6465]])
Targets are:
tensor([3151,  482, 1366, 6464, 3151,  482, 1366, 6465, 6973,  483, 1366, 6465,
        6973,  483, 5100, 6466])
Data is:
tensor([[6973,  483, 5100, 6466],
        [6973,  483, 5101, 6466],
        [3142,  484, 5101, 6466],
        [3142,  484, 5101, 6467]])
Targets are:
tensor([6973,  483, 5101, 6466, 3142,  484, 5101, 6466, 3142,  484, 5101, 6467,
        3142,  484, 5102, 6467])
Data is:
tensor([[3142,  484, 5102, 6467],
        [3142,  484, 5103, 6468],
        [3142,  485, 5103, 6468],
        [3142,  485, 5104, 6468]])
Targets are:
tensor([3142,  484, 5103,

Data is:
tensor([[4190, 7903,  318, 5162],
        [   5, 7903,  318, 5162],
        [4190, 7903,  318, 5162],
        [  36, 7903,  318, 5162]])
Targets are:
tensor([   5, 7903,  318, 5162, 4190, 7903,  318, 5162,   36, 7903,  318, 5162,
        4190, 7903,  318, 1448])
Data is:
tensor([[4190, 7903,  318, 1448],
        [  15, 7903, 4294, 1448],
        [ 188, 6879, 4294, 1448],
        [  22, 6879, 4294, 5163]])
Targets are:
tensor([  15, 7903, 4294, 1448,  188, 6879, 4294, 1448,   22, 6879, 4294, 5163,
         188, 6879, 4295, 5163])
Data is:
tensor([[ 188, 6879, 4295, 5163],
        [  30, 3000,  319, 5163],
        [ 188, 3000,  319, 1449],
        [  20, 3000,  319, 1449]])
Targets are:
tensor([  30, 3000,  319, 5163,  188, 3000,  319, 1449,   20, 3000,  319, 1449,
         188, 3000, 4296, 1449])
Data is:
tensor([[ 188, 3000, 4296, 1449],
        [  21, 3000, 4297, 1449],
        [ 188, 3000, 4297, 1449],
        [   8, 3001, 4297, 5164]])
Targets are:
tensor([  21, 3000, 4297,

Data is:
tensor([[4206, 3062,  385, 5388],
        [   5, 3062,  385, 5388],
        [ 198, 3064,  385, 5388],
        [  19, 3064,  385, 5389]])
Targets are:
tensor([   5, 3062,  385, 5388,  198, 3064,  385, 5388,   19, 3064,  385, 5389,
         198, 3065,  386, 5389])
Data is:
tensor([[ 198, 3065,  386, 5389],
        [   2, 3065,  386, 7763],
        [ 199, 3065,  387, 7763],
        [   3, 3065,  387, 7763]])
Targets are:
tensor([   2, 3065,  386, 7763,  199, 3065,  387, 7763,    3, 3065,  387, 7763,
         199, 3066,  388, 1669])
Data is:
tensor([[ 199, 3066,  388, 1669],
        [   3, 3066,  388, 1669],
        [ 200, 3066,  388, 7764],
        [  12, 3067,  388, 7764]])
Targets are:
tensor([   3, 3066,  388, 1669,  200, 3066,  388, 7764,   12, 3067,  388, 7764,
         200, 3067,  376, 1670])
Data is:
tensor([[ 200, 3067,  376, 1670],
        [   2, 3069,  376, 1670],
        [4207, 3069,  377, 1671],
        [   1, 3069,  377, 1671]])
Targets are:
tensor([   2, 3069,  376,

Data is:
tensor([[4238, 6951, 4527, 1714],
        [   1, 6951, 4527, 1714],
        [4238, 6951,  646, 1714],
        [  16, 6951,  646, 1714]])
Targets are:
tensor([   1, 6951, 4527, 1714, 4238, 6951,  646, 1714,   16, 6951,  646, 1714,
        4239, 6951,  646, 1715])
Data is:
tensor([[4239, 6951,  646, 1715],
        [   5, 6951,  646, 1715],
        [4239, 6951,  647, 1715],
        [   8, 6952,  647, 7767]])
Targets are:
tensor([   5, 6951,  646, 1715, 4239, 6951,  647, 1715,    8, 6952,  647, 7767,
        4240, 6952,  648, 7767])
Data is:
tensor([[4240, 6952,  648, 7767],
        [   7, 6952,  648, 7767],
        [4240, 6953,  648, 5418],
        [   8, 6953,  648, 5418]])
Targets are:
tensor([   7, 6952,  648, 7767, 4240, 6953,  648, 5418,    8, 6953,  648, 5418,
        4240, 6953,  648, 5418])
Data is:
tensor([[4240, 6953,  648, 5418],
        [   8, 6954,  648, 5418],
        [4240, 3114, 4528, 5418],
        [   2, 7009, 4528, 5420]])
Targets are:
tensor([   8, 6954,  648,

Data is:
tensor([[  49, 3385,  692, 5261],
        [  12, 3385,  692, 5261],
        [  50, 3385,  692, 5262],
        [   9, 3385,  693, 5262]])
Targets are:
tensor([  12, 3385,  692, 5261,   50, 3385,  692, 5262,    9, 3385,  693, 5262,
          50, 3386,  693, 1615])
Data is:
tensor([[  50, 3386,  693, 1615],
        [   9, 3386,  693, 1615],
        [  50, 3386,  693, 1615],
        [   6, 3386,  693, 1615]])
Targets are:
tensor([   9, 3386,  693, 1615,   50, 3386,  693, 1615,    6, 3386,  693, 1615,
          51, 3387, 4550, 1617])
Data is:
tensor([[  51, 3387, 4550, 1617],
        [   2, 3387,  497, 1617],
        [  51, 3387,  502, 1617],
        [   1, 3387,  502, 1617]])
Targets are:
tensor([   2, 3387,  497, 1617,   51, 3387,  502, 1617,    1, 3387,  502, 1617,
          51, 3388,  502, 1618])
Data is:
tensor([[  51, 3388,  502, 1618],
        [   0, 3388,  504, 1618],
        [  51, 3388,  504, 1618],
        [   1, 3389,  505, 1618]])
Targets are:
tensor([   0, 3388,  504,

Data is:
tensor([[  79, 3225, 4438, 5354],
        [  10, 3225, 4438, 5355],
        [  79, 3225, 4440, 5355],
        [   8, 3226, 4440, 5355]])
Targets are:
tensor([  10, 3225, 4438, 5355,   79, 3225, 4440, 5355,    8, 3226, 4440, 5355,
          80, 3226,  557, 5355])
Data is:
tensor([[  80, 3226,  557, 5355],
        [   2, 3226, 4447, 5356],
        [  80, 3226, 4447, 5356],
        [   5, 3226, 4447, 5356]])
Targets are:
tensor([   2, 3226, 4447, 5356,   80, 3226, 4447, 5356,    5, 3226, 4447, 5356,
          80, 3227, 4447, 5356])
Data is:
tensor([[  80, 3227, 4447, 5356],
        [  29, 3227,  558, 5358],
        [  80, 3227,  558, 5358],
        [   4, 3227, 4448, 5359]])
Targets are:
tensor([  29, 3227,  558, 5358,   80, 3227,  558, 5358,    4, 3227, 4448, 5359,
          80, 3227, 4448, 5359])
Data is:
tensor([[  80, 3227, 4448, 5359],
        [   0, 3228, 4448, 5359],
        [  83, 3229, 4448, 5359],
        [   9, 3229,  559, 5360]])
Targets are:
tensor([   0, 3228, 4448,

Data is:
tensor([[4133, 3283,  588, 5611],
        [  28, 3291,  588, 5612],
        [ 118, 3291, 4489, 5612],
        [  19, 3291, 4489, 5612]])
Targets are:
tensor([  28, 3291,  588, 5612,  118, 3291, 4489, 5612,   19, 3291, 4489, 5612,
         118, 3291, 4490, 5612])
Data is:
tensor([[ 118, 3291, 4490, 5612],
        [  13, 3297, 4490, 5612],
        [ 106, 3297, 4490, 5613],
        [   2, 3297, 4490, 5613]])
Targets are:
tensor([  13, 3297, 4490, 5612,  106, 3297, 4490, 5613,    2, 3297, 4490, 5613,
         106, 7052, 4491, 1809])
Data is:
tensor([[ 106, 7052, 4491, 1809],
        [   1, 7052, 4491, 1809],
        [ 106, 7052, 4491, 5614],
        [   1, 3298,  607, 5614]])
Targets are:
tensor([   1, 7052, 4491, 1809,  106, 7052, 4491, 5614,    1, 3298,  607, 5614,
         106, 3298,  607, 5614])
Data is:
tensor([[ 106, 3298,  607, 5614],
        [   3, 3298,  610, 5614],
        [4131, 3298, 4507, 1814],
        [  13, 3299,  612, 1814]])
Targets are:
tensor([   3, 3298,  610,

Data is:
tensor([[ 149, 7157,  853, 1863],
        [   3, 7157,  853, 1863],
        [ 150, 7157,  854, 1863],
        [   1, 7157,  854, 5673]])
Targets are:
tensor([   3, 7157,  853, 1863,  150, 7157,  854, 1863,    1, 7157,  854, 5673,
         150, 7157,  855, 5673])
Data is:
tensor([[ 150, 7157,  855, 5673],
        [   6, 3446,  855, 5674],
        [ 150, 3446,  855, 5674],
        [   3, 3446,  855, 5674]])
Targets are:
tensor([   6, 3446,  855, 5674,  150, 3446,  855, 5674,    3, 3446,  855, 5674,
         150, 7158,  855, 5674])
Data is:
tensor([[ 150, 7158,  855, 5674],
        [  18, 7158,  855, 5675],
        [ 151, 7158, 7691, 5676],
        [   1, 7158, 7691, 1738]])
Targets are:
tensor([  18, 7158,  855, 5675,  151, 7158, 7691, 5676,    1, 7158, 7691, 1738,
         151, 7158, 7691, 1740])
Data is:
tensor([[ 151, 7158, 7691, 1740],
        [   1, 3447, 7691, 1740],
        [ 151, 3447, 7691, 1740],
        [   3, 7946, 7692, 1741]])
Targets are:
tensor([   1, 3447, 7691,

Data is:
tensor([[6171, 7285,  715, 5500],
        [6172, 7285, 4567, 5501],
        [6172, 7286, 4567, 5501],
        [6173, 7286, 4567, 5501]])
Targets are:
tensor([6172, 7285, 4567, 5501, 6172, 7286, 4567, 5501, 6173, 7286, 4567, 5501,
        6173, 7286,  717, 5502])
Data is:
tensor([[6173, 7286,  717, 5502],
        [6173, 7287,  717, 5502],
        [6173, 7961,  717, 5502],
        [6174, 7961,  717, 5502]])
Targets are:
tensor([6173, 7287,  717, 5502, 6173, 7961,  717, 5502, 6174, 7961,  717, 5502,
        6174, 7961,  718, 5502])
Data is:
tensor([[6174, 7961,  718, 5502],
        [6174, 7288,  719, 5503],
        [6174, 7288,  719, 5503],
        [6174, 7288,  719, 5503]])
Targets are:
tensor([6174, 7288,  719, 5503, 6174, 7288,  719, 5503, 6174, 7288,  719, 5503,
        6163, 7288,  720, 5504])
Data is:
tensor([[6163, 7288,  720, 5504],
        [6163, 7288,  720, 7774],
        [6163, 7289,  720, 7774],
        [6164, 7289,  720, 7774]])
Targets are:
tensor([6163, 7288,  720,

Data is:
tensor([[2346, 7160, 4594, 5582],
        [2346, 7160,  759, 5582],
        [2346, 7160, 4595, 1791],
        [6281, 7160, 4595, 1791]])
Targets are:
tensor([2346, 7160,  759, 5582, 2346, 7160, 4595, 1791, 6281, 7160, 4595, 1791,
        6281, 7160, 4595, 1791])
Data is:
tensor([[6281, 7160, 4595, 1791],
        [6281, 7161, 4596, 5573],
        [6281, 7161, 4596, 5573],
        [6284, 7161, 4596, 1783]])
Targets are:
tensor([6281, 7161, 4596, 5573, 6281, 7161, 4596, 5573, 6284, 7161, 4596, 1783,
        6284, 3454, 4597, 1783])
Data is:
tensor([[6284, 3454, 4597, 1783],
        [6284, 3454, 4597, 5574],
        [6284, 3454, 4597, 5574],
        [6284, 3454, 4598, 5574]])
Targets are:
tensor([6284, 3454, 4597, 5574, 6284, 3454, 4597, 5574, 6284, 3454, 4598, 5574,
        6285, 3454, 4598, 1784])
Data is:
tensor([[6285, 3454, 4598, 1784],
        [6285, 3454, 4598, 1784],
        [6286, 3454, 4599, 1784],
        [6286, 7163, 4600, 5575]])
Targets are:
tensor([6285, 3454, 4598,

Data is:
tensor([[2191, 7195, 4646, 1980],
        [2192, 7195, 4647, 1980],
        [6183, 7195, 4647, 1980],
        [6185, 3511, 4647, 1980]])
Targets are:
tensor([2192, 7195, 4647, 1980, 6183, 7195, 4647, 1980, 6185, 3511, 4647, 1980,
        6185, 3511, 4647, 1981])
Data is:
tensor([[6185, 3511, 4647, 1981],
        [6185, 7196, 4647, 1981],
        [6185, 3512, 4648, 1981],
        [6186, 3512, 4648, 1982]])
Targets are:
tensor([6185, 7196, 4647, 1981, 6185, 3512, 4648, 1981, 6186, 3512, 4648, 1982,
        6186, 7197, 4648, 1982])
Data is:
tensor([[6186, 7197, 4648, 1982],
        [6187, 7197, 4648, 1982],
        [6187, 7197, 4649, 1982],
        [6187, 3517, 4649, 5865]])
Targets are:
tensor([6187, 7197, 4648, 1982, 6187, 7197, 4649, 1982, 6187, 3517, 4649, 5865,
        7797, 3517, 4649, 5865])
Data is:
tensor([[7797, 3517, 4649, 5865],
        [7797, 3517, 4649, 5865],
        [7797, 3517, 4649, 5865],
        [7797, 3522,  809, 5865]])
Targets are:
tensor([7797, 3517, 4649,

Data is:
tensor([[2256, 3579, 1062, 5895],
        [2244, 3579, 1062, 5896],
        [2245, 3579, 1062, 5896],
        [2246, 3580, 1063, 5896]])
Targets are:
tensor([2244, 3579, 1062, 5896, 2245, 3579, 1062, 5896, 2246, 3580, 1063, 5896,
        2246, 3580, 1063, 5896])
Data is:
tensor([[2246, 3580, 1063, 5896],
        [2246, 3581, 1063, 5897],
        [2247, 3581, 1064, 5897],
        [2247, 3581, 1065, 5898]])
Targets are:
tensor([2246, 3581, 1063, 5897, 2247, 3581, 1064, 5897, 2247, 3581, 1065, 5898,
        2247, 7253, 1065, 5898])
Data is:
tensor([[2247, 7253, 1065, 5898],
        [2247, 7253, 1066, 5898],
        [2247, 7253, 1054, 2029],
        [2248, 3572, 1054, 2029]])
Targets are:
tensor([2247, 7253, 1066, 5898, 2247, 7253, 1054, 2029, 2248, 3572, 1054, 2029,
        2248, 7245, 1054, 2029])
Data is:
tensor([[2248, 7245, 1054, 2029],
        [7806, 7245, 1054, 2029],
        [7806, 7246, 1054, 2029],
        [7806, 7246, 1054, 2037]])
Targets are:
tensor([7806, 7245, 1054,

Data is:
tensor([[2326, 7428, 4875, 5750],
        [2326, 8001, 4875, 5750],
        [2326, 8001, 1109, 1914],
        [2326, 3820, 1109, 1914]])
Targets are:
tensor([2326, 8001, 4875, 5750, 2326, 8001, 1109, 1914, 2326, 3820, 1109, 1914,
        2328, 3820, 4876, 1914])
Data is:
tensor([[2328, 3820, 4876, 1914],
        [2328, 3820, 4876, 1914],
        [2328, 8002, 4877, 1914],
        [2329, 8002, 4877, 1915]])
Targets are:
tensor([2328, 3820, 4876, 1914, 2328, 8002, 4877, 1914, 2329, 8002, 4877, 1915,
        2329, 8002, 4877, 1915])
Data is:
tensor([[2329, 8002, 4877, 1915],
        [2329, 3821, 4878, 1915],
        [2317, 3821, 4878, 1915],
        [2317, 3821, 4878, 1915]])
Targets are:
tensor([2329, 3821, 4878, 1915, 2317, 3821, 4878, 1915, 2317, 3821, 4878, 1915,
        2317, 3821, 4879, 5751])
Data is:
tensor([[2317, 3821, 4879, 5751],
        [2317, 8000, 4880, 5751],
        [2318, 3810, 1125, 5752],
        [2318, 3810, 1125, 5739]])
Targets are:
tensor([2317, 8000, 4880,

Data is:
tensor([[6675, 3667,  979, 5809],
        [6675, 3667,  979, 5820],
        [6675, 3668,  979, 5820],
        [2719, 3668,  979, 5820]])
Targets are:
tensor([6675, 3667,  979, 5820, 6675, 3668,  979, 5820, 2719, 3668,  979, 5820,
        2719, 7321,  979, 5822])
Data is:
tensor([[2719, 7321,  979, 5822],
        [2719, 7321,  979, 5822],
        [6676, 7321,  982, 5822],
        [6676, 7321,  983, 5822]])
Targets are:
tensor([2719, 7321,  979, 5822, 6676, 7321,  982, 5822, 6676, 7321,  983, 5822,
        6676, 7322,  983, 5822])
Data is:
tensor([[6676, 7322,  983, 5822],
        [2720, 7323,  983, 5823],
        [2720, 7323,  983, 5823],
        [2720, 7323,  983, 5823]])
Targets are:
tensor([2720, 7323,  983, 5823, 2720, 7323,  983, 5823, 2720, 7323,  983, 5823,
        2720, 7323,  984, 5824])
Data is:
tensor([[2720, 7323,  984, 5824],
        [6677, 7323,  984, 5824],
        [6677, 7323,  984, 5825],
        [6677, 3669,  985, 5825]])
Targets are:
tensor([6677, 7323,  984,

Data is:
tensor([[2756, 3726, 1023, 2127],
        [6707, 7349, 1023, 6097],
        [6707, 7349, 1023, 6097],
        [2757, 7349, 4815, 6097]])
Targets are:
tensor([6707, 7349, 1023, 6097, 6707, 7349, 1023, 6097, 2757, 7349, 4815, 6097,
        2757, 7349, 4815, 2128])
Data is:
tensor([[2757, 7349, 4815, 2128],
        [2757, 7349, 4815, 2128],
        [6708, 3727, 4815, 2128],
        [6708, 3727, 4815, 2128]])
Targets are:
tensor([2757, 7349, 4815, 2128, 6708, 3727, 4815, 2128, 6708, 3727, 4815, 2128,
        6708, 3727, 4815, 6098])
Data is:
tensor([[6708, 3727, 4815, 6098],
        [6708, 3727, 4815, 6099],
        [6708, 3727, 1024, 6100],
        [6708, 7350, 1024, 6100]])
Targets are:
tensor([6708, 3727, 4815, 6099, 6708, 3727, 1024, 6100, 6708, 7350, 1024, 6100,
        2758, 7350, 1024, 6101])
Data is:
tensor([[2758, 7350, 1024, 6101],
        [6566, 7350, 4816, 6102],
        [6566, 7350, 4816, 6102],
        [6566, 7351, 4816, 6102]])
Targets are:
tensor([6566, 7350, 4816,

Data is:
tensor([[7843, 3789, 5035, 7792],
        [7843, 3790, 5035, 2177],
        [7843, 3790, 5035, 2177],
        [7843, 3790, 5035, 2177]])
Targets are:
tensor([7843, 3790, 5035, 2177, 7843, 3790, 5035, 2177, 7843, 3790, 5035, 2177,
        2601, 3791, 1243, 2178])
Data is:
tensor([[2601, 3791, 1243, 2178],
        [2601, 3791, 5036, 2178],
        [2601, 3791, 5037, 6160],
        [2602, 7409, 7726, 6160]])
Targets are:
tensor([2601, 3791, 5036, 2178, 2601, 3791, 5037, 6160, 2602, 7409, 7726, 6160,
        6595, 7409, 7726, 6160])
Data is:
tensor([[6595, 7409, 7726, 6160],
        [2603, 7409, 7727, 6161],
        [2603, 7409, 7727, 6161],
        [6596, 3783, 7728, 6152]])
Targets are:
tensor([2603, 7409, 7727, 6161, 2603, 7409, 7727, 6161, 6596, 3783, 7728, 6152,
        6596, 7400, 7728, 6152])
Data is:
tensor([[6596, 7400, 7728, 6152],
        [6596, 7400, 7728, 6152],
        [6597, 7401, 7728, 2171],
        [6597, 7401, 7728, 2171]])
Targets are:
tensor([6596, 7400, 7728,

tensor([2687, 7578, 1313, 5968, 2687, 7578, 1313, 5969, 2687, 7578, 1303, 5969,
        2687, 7578, 1303, 5969])
Data is:
tensor([[2687, 7578, 1303, 5969],
        [2688, 4030, 1304, 5969],
        [2688, 7579, 1304, 5969],
        [2688, 7579, 1304, 5969]])
Targets are:
tensor([2688, 4030, 1304, 5969, 2688, 7579, 1304, 5969, 2688, 7579, 1304, 5969,
        2689, 7579, 1304, 5970])
Data is:
tensor([[2689, 7579, 1304, 5970],
        [2690, 4031, 1304, 5970],
        [2690, 4031, 1305, 5970],
        [2690, 4031, 5061, 5970]])
Targets are:
tensor([2690, 4031, 1304, 5970, 2690, 4031, 1305, 5970, 2690, 4031, 5061, 5970,
        2690, 4031, 5061, 5970])
Data is:
tensor([[2690, 4031, 5061, 5970],
        [2691, 4031, 5061, 5971],
        [2680, 7580, 1306, 5971],
        [2680, 7580, 1306, 5971]])
Targets are:
tensor([2691, 4031, 5061, 5971, 2680, 7580, 1306, 5971, 2680, 7580, 1306, 5971,
        2680, 7580, 1306, 5971])
Data is:
tensor([[2680, 7580, 1306, 5971],
        [2680, 7580, 1306, 5

Data is:
tensor([[6823, 3886, 4921, 6055],
        [6823, 3886, 4921, 2102],
        [6823, 3887, 4921, 2102],
        [6823, 3887, 1173, 6056]])
Targets are:
tensor([6823, 3886, 4921, 2102, 6823, 3887, 4921, 2102, 6823, 3887, 1173, 6056,
        2923, 3887, 1173, 6056])
Data is:
tensor([[2923, 3887, 1173, 6056],
        [2923, 3887, 1176, 6056],
        [2923, 3887, 1176, 6056],
        [7889, 3887, 1176, 2103]])
Targets are:
tensor([2923, 3887, 1176, 6056, 2923, 3887, 1176, 6056, 7889, 3887, 1176, 2103,
        7889, 3887, 1176, 2103])
Data is:
tensor([[7889, 3887, 1176, 2103],
        [7889, 3888, 1177, 2103],
        [7889, 3888, 1177, 2103],
        [7889, 3888, 1177, 6057]])
Targets are:
tensor([7889, 3888, 1177, 2103, 7889, 3888, 1177, 2103, 7889, 3888, 1177, 6057,
        2924, 3877, 1177, 6057])
Data is:
tensor([[2924, 3877, 1177, 6057],
        [2924, 3877, 1178, 6057],
        [2924, 3877, 1179, 6057],
        [2924, 3878, 1179, 2104]])
Targets are:
tensor([2924, 3877, 1178,

Data is:
tensor([[2768, 3939, 4989, 2485],
        [2768, 3939, 4989, 2485],
        [2768, 7504, 1219, 2485],
        [2769, 7504, 1220, 2485]])
Targets are:
tensor([2768, 3939, 4989, 2485, 2768, 7504, 1219, 2485, 2769, 7504, 1220, 2485,
        2769, 3940, 1220, 2486])
Data is:
tensor([[2769, 3940, 1220, 2486],
        [2769, 7505, 1220, 2486],
        [2769, 7505, 4990, 2487],
        [2769, 7505, 4990, 2487]])
Targets are:
tensor([2769, 7505, 1220, 2486, 2769, 7505, 4990, 2487, 2769, 7505, 4990, 2487,
        2769, 7505, 4990, 2487])
Data is:
tensor([[2769, 7505, 4990, 2487],
        [2769, 3941, 4990, 2488],
        [2770, 7506, 4990, 2488],
        [2770, 7506, 4990, 2488]])
Targets are:
tensor([2769, 3941, 4990, 2488, 2770, 7506, 4990, 2488, 2770, 7506, 4990, 2488,
        2770, 7506, 1221, 2488])
Data is:
tensor([[2770, 7506, 1221, 2488],
        [2770, 7506, 1221, 2488],
        [2770, 3942, 1221, 2489],
        [2771, 3942, 4978, 2489]])
Targets are:
tensor([2770, 7506, 1221,

Data is:
tensor([[2841, 7542, 1488, 2537],
        [2841, 7542, 1488, 2537],
        [2841, 7542, 1489, 2538],
        [2842, 3995, 1489, 2538]])
Targets are:
tensor([2841, 7542, 1488, 2537, 2841, 7542, 1489, 2538, 2842, 3995, 1489, 2538,
        2842, 3995, 5179, 2538])
Data is:
tensor([[2842, 3995, 5179, 2538],
        [2829, 3995, 5179, 2539],
        [2829, 3995, 5179, 2539],
        [2830, 3995, 1490, 2539]])
Targets are:
tensor([2829, 3995, 5179, 2539, 2829, 3995, 5179, 2539, 2830, 3995, 1490, 2539,
        2830, 3995, 1490, 6556])
Data is:
tensor([[2830, 3995, 1490, 6556],
        [2830, 3997, 1490, 6556],
        [2830, 3997, 5180, 2540],
        [2831, 3997, 5180, 2540]])
Targets are:
tensor([2830, 3997, 1490, 6556, 2830, 3997, 5180, 2540, 2831, 3997, 5180, 2540,
        2831, 3997, 5180, 2540])
Data is:
tensor([[2831, 3997, 5180, 2540],
        [2831, 4000, 5180, 2534],
        [2831, 4000, 5180, 2534],
        [2832, 4001, 1478, 6546]])
Targets are:
tensor([2831, 4000, 5180,

tensor([6794,  413, 1551, 6380, 6794,  413, 1551, 6380, 2900, 4368, 1551, 6381,
        2900, 4368, 1551, 6382])
Data is:
tensor([[2900, 4368, 1551, 6382],
        [2900, 4370, 1551, 6382],
        [2900, 4370, 1551, 6384],
        [6795, 4370, 1551, 2428]])
Targets are:
tensor([2900, 4370, 1551, 6382, 2900, 4370, 1551, 6384, 6795, 4370, 1551, 2428,
        6796, 4371, 1551, 2428])
Data is:
tensor([[6796, 4371, 1551, 2428],
        [6798, 4372, 1551, 2428],
        [2972, 4372, 5201, 2428],
        [2972, 4372, 5201, 2431]])
Targets are:
tensor([6798, 4372, 1551, 2428, 2972, 4372, 5201, 2428, 2972, 4372, 5201, 2431,
        2972, 4373, 5201, 2431])
Data is:
tensor([[2972, 4373, 5201, 2431],
        [2972, 4373, 5201, 2431],
        [2972, 4374, 5202, 2431],
        [2972, 4374, 5202, 2432]])
Targets are:
tensor([2972, 4373, 5201, 2431, 2972, 4374, 5202, 2431, 2972, 4374, 5202, 2432,
        2972, 4374, 1553, 2432])
Data is:
tensor([[2972, 4374, 1553, 2432],
        [6866, 7649, 1553, 6

Data is:
tensor([[6984, 4260, 5109, 2454],
        [6985, 4261, 1376, 2454],
        [6986, 4261, 1376, 2454],
        [6986, 4261, 1376, 2455]])
Targets are:
tensor([6985, 4261, 1376, 2454, 6986, 4261, 1376, 2454, 6986, 4261, 1376, 2455,
        6986, 4261, 1376, 2455])
Data is:
tensor([[6986, 4261, 1376, 2455],
        [6986, 4261, 1376, 6487],
        [6986, 4262, 5110, 6487],
        [6986, 4263, 5110, 6488]])
Targets are:
tensor([6986, 4261, 1376, 6487, 6986, 4262, 5110, 6487, 6986, 4263, 5110, 6488,
        6986, 4263, 1377, 6488])
Data is:
tensor([[6986, 4263, 1377, 6488],
        [6987, 4263, 1377, 2456],
        [7923, 4263, 5111, 2456],
        [7923, 7643, 5111, 2456]])
Targets are:
tensor([6987, 4263, 1377, 2456, 7923, 4263, 5111, 2456, 7923, 7643, 5111, 2456,
        7924, 7643, 5111, 6489])
Data is:
tensor([[7924, 7643, 5111, 6489],
        [7924, 7643, 1378, 6490],
        [3152, 7643, 1378, 6490],
        [3152, 7643, 1380, 6490]])
Targets are:
tensor([7924, 7643, 1378,

Data is:
tensor([[7627, 2992,  306, 1432],
        [   1, 2992,  306, 5145],
        [7628, 2994,  306, 5145],
        [  10, 2994,  307, 5145]])
Targets are:
tensor([   1, 2992,  306, 5145, 7628, 2994,  306, 5145,   10, 2994,  307, 5145,
         162, 2994, 4288, 5145])
Data is:
tensor([[ 162, 2994, 4288, 5145],
        [   6, 2994, 4288, 5145],
        [ 162, 2994, 4288, 5146],
        [   4, 2994, 4288, 5146]])
Targets are:
tensor([   6, 2994, 4288, 5145,  162, 2994, 4288, 5146,    4, 2994, 4288, 5146,
         162, 2994, 4289, 5146])
Data is:
tensor([[ 162, 2994, 4289, 5146],
        [   5, 7904, 4289, 5146],
        [ 163, 7904, 4289, 5147],
        [   5, 7904, 4289, 5147]])
Targets are:
tensor([   5, 7904, 4289, 5146,  163, 7904, 4289, 5147,    5, 7904, 4289, 5147,
         163, 7904, 4290, 5148])
Data is:
tensor([[ 163, 7904, 4290, 5148],
        [   1, 6880, 4290, 5148],
        [ 163, 6880, 4291, 5148],
        [   5, 3002, 4292, 5148]])
Targets are:
tensor([   1, 6880, 4290,

Data is:
tensor([[4209, 3054, 4342, 1655],
        [   4, 3054, 4343, 1655],
        [ 203, 3054, 4343, 1656],
        [  16, 3054, 4343, 1656]])
Targets are:
tensor([   4, 3054, 4343, 1655,  203, 3054, 4343, 1656,   16, 3054, 4343, 1656,
         203, 3054, 4344, 1656])
Data is:
tensor([[ 203, 3054, 4344, 1656],
        [   8, 3055, 4344, 1657],
        [ 203, 3055, 4344, 1657],
        [   4, 3055,  358, 1657]])
Targets are:
tensor([   8, 3055, 4344, 1657,  203, 3055, 4344, 1657,    4, 3055,  358, 1657,
         203, 6902,  358, 1657])
Data is:
tensor([[ 203, 6902,  358, 1657],
        [   0, 6902, 4332, 1657],
        [4210, 6902, 4332, 1657],
        [  16, 3056, 4332, 1658]])
Targets are:
tensor([   0, 6902, 4332, 1657, 4210, 6902, 4332, 1657,   16, 3056, 4332, 1658,
        4210, 3056, 4332, 1658])
Data is:
tensor([[4210, 3056, 4332, 1658],
        [  16, 3056, 4333, 1658],
        [4210, 6903, 4333, 1658],
        [  22, 6903, 4334, 1658]])
Targets are:
tensor([  16, 3056, 4333,

Data is:
tensor([[ 222, 6938, 4512, 1706],
        [  19, 6938, 4512, 1707],
        [4233, 6938, 4512, 1707],
        [   1, 6938, 4512, 1707]])
Targets are:
tensor([  19, 6938, 4512, 1707, 4233, 6938, 4512, 1707,    1, 6938, 4512, 1707,
        4233, 6938, 4512, 1707])
Data is:
tensor([[4233, 6938, 4512, 1707],
        [   6, 6938, 4512, 1707],
        [4233, 3099,  618, 1708],
        [   5, 3099,  618, 1708]])
Targets are:
tensor([   6, 6938, 4512, 1707, 4233, 3099,  618, 1708,    5, 3099,  618, 1708,
         223, 3099,  618, 1709])
Data is:
tensor([[ 223, 3099,  618, 1709],
        [  29, 3099,  618, 1700],
        [ 223, 7914,  618, 1700],
        [  17, 7914,  618, 1700]])
Targets are:
tensor([  29, 3099,  618, 1700,  223, 7914,  618, 1700,   17, 7914,  618, 1700,
         223, 7914, 4513, 1700])
Data is:
tensor([[ 223, 7914, 4513, 1700],
        [   9, 7914, 4513, 1700],
        [ 223, 3091, 4513, 5409],
        [   6, 3091,  619, 5409]])
Targets are:
tensor([   9, 7914, 4513,

tensor([  10, 7095,  668, 5236, 4243, 3363,  668, 5236,    0, 3363,  668, 5237,
        4243, 3363,  668, 5237])
Data is:
tensor([[4243, 3363,  668, 5237],
        [   3, 3364, 4537, 5237],
        [ 235, 3364, 4537, 5237],
        [   9, 3364, 4537, 5238]])
Targets are:
tensor([   3, 3364, 4537, 5237,  235, 3364, 4537, 5237,    9, 3364, 4537, 5238,
         235, 3364, 4537, 5238])
Data is:
tensor([[ 235, 3364, 4537, 5238],
        [  28, 3365,  673, 5239],
        [ 235, 3365,  673, 5239],
        [  33, 3365,  680, 5239]])
Targets are:
tensor([  28, 3365,  673, 5239,  235, 3365,  673, 5239,   33, 3365,  680, 5239,
        4244, 3365,  681, 1600])
Data is:
tensor([[4244, 3365,  681, 1600],
        [   4, 3366,  681, 1600],
        [4244, 3366,  681, 1600],
        [   0, 3366,  681, 1602]])
Targets are:
tensor([   4, 3366,  681, 1600, 4244, 3366,  681, 1600,    0, 3366,  681, 1602,
        4244, 3367,  682, 1602])
Data is:
tensor([[4244, 3367,  682, 1602],
        [   1, 3367,  682, 1

Data is:
tensor([[4104, 3421, 4413, 1627],
        [  26, 3422, 4414, 1627],
        [4104, 3422, 4414, 1627],
        [8040, 3422, 4414, 1628]])
Targets are:
tensor([  26, 3422, 4414, 1627, 4104, 3422, 4414, 1627, 8040, 3422, 4414, 1628,
        4104, 3422, 4414, 1628])
Data is:
tensor([[4104, 3422, 4414, 1628],
        [  18, 3423, 4415, 1628],
        [  65, 3423, 4415, 1628],
        [  23, 3423, 4415, 1628]])
Targets are:
tensor([  18, 3423, 4415, 1628,   65, 3423, 4415, 1628,   23, 3423, 4415, 1628,
          65, 7143, 4416, 1629])
Data is:
tensor([[  65, 7143, 4416, 1629],
        [   1, 7143, 4416, 1629],
        [  65, 7143, 4416, 1630],
        [  12, 7143, 4416, 1630]])
Targets are:
tensor([   1, 7143, 4416, 1629,   65, 7143, 4416, 1630,   12, 7143, 4416, 1630,
        4105, 7143, 4417, 1630])
Data is:
tensor([[4105, 7143, 4417, 1630],
        [   1, 7144, 4417, 1631],
        [4105, 7144, 4417, 1631],
        [  11, 7144, 4417, 7752]])
Targets are:
tensor([   1, 7144, 4417,

tensor([[ 103, 7038,  569, 5436],
        [  12, 7038, 4463, 5436],
        [ 103, 7038,  570, 5436],
        [   2, 7038,  570, 5436]])
Targets are:
tensor([  12, 7038, 4463, 5436,  103, 7038,  570, 5436,    2, 7038,  570, 5436,
         103, 7038,  570, 5437])
Data is:
tensor([[ 103, 7038,  570, 5437],
        [   1, 7038,  570, 5437],
        [ 103, 3258,  570, 5437],
        [  10, 3258, 4464, 5437]])
Targets are:
tensor([   1, 7038,  570, 5437,  103, 3258,  570, 5437,   10, 3258, 4464, 5437,
         103, 3258, 4464, 5438])
Data is:
tensor([[ 103, 3258, 4464, 5438],
        [   2, 3258, 4464, 5438],
        [ 104, 3266,  571, 1733],
        [   5, 3266,  571, 1733]])
Targets are:
tensor([   2, 3258, 4464, 5438,  104, 3266,  571, 1733,    5, 3266,  571, 1733,
         104, 3266,  571, 1733])
Data is:
tensor([[ 104, 3266,  571, 1733],
        [   5, 3266,  571, 5439],
        [ 104, 3267,  571, 5439],
        [   4, 3267, 4465, 5439]])
Targets are:
tensor([   5, 3266,  571, 5439,  1

Data is:
tensor([[ 122, 7061,  702, 1833],
        [  37, 7061,  702, 1836],
        [ 122, 7061,  702, 1836],
        [  10, 3315,  702, 1837]])
Targets are:
tensor([  37, 7061,  702, 1836,  122, 7061,  702, 1836,   10, 3315,  702, 1837,
         123, 3315,  703, 1837])
Data is:
tensor([[ 123, 3315,  703, 1837],
        [  13, 3315,  703, 1837],
        [ 123, 3315,  703, 1838],
        [  14, 3323,  703, 1838]])
Targets are:
tensor([  13, 3315,  703, 1837,  123, 3315,  703, 1838,   14, 3323,  703, 1838,
         123, 3323,  703, 1838])
Data is:
tensor([[ 123, 3323,  703, 1838],
        [  29, 3323,  703, 1838],
        [ 124, 3323,  704, 1839],
        [   7, 3323,  704, 1840]])
Targets are:
tensor([  29, 3323,  703, 1838,  124, 3323,  704, 1839,    7, 3323,  704, 1840,
         124, 3324,  704, 1840])
Data is:
tensor([[ 124, 3324,  704, 1840],
        [   9, 3324,  704, 1840],
        [ 124, 3325,  704, 1840],
        [   5, 3325,  704, 1841]])
Targets are:
tensor([   9, 3324,  704,

Data is:
tensor([[4153, 3564, 7695, 1748],
        [  28, 3564, 4692, 5466],
        [4153, 3564, 4692, 1749],
        [   6, 3564, 4692, 1749]])
Targets are:
tensor([  28, 3564, 4692, 5466, 4153, 3564, 4692, 1749,    6, 3564, 4692, 1749,
        4153, 7237,  882, 1749])
Data is:
tensor([[4153, 7237,  882, 1749],
        [   9, 7237,  882, 7772],
        [4154, 7237, 7696, 7772],
        [   1, 7237, 7696, 7772]])
Targets are:
tensor([   9, 7237,  882, 7772, 4154, 7237, 7696, 7772,    1, 7237, 7696, 7772,
        4154, 3565, 7696, 5467])
Data is:
tensor([[4154, 3565, 7696, 5467],
        [  24, 3565, 7696, 5467],
        [ 158, 3565,  883, 5467],
        [  12, 3565,  883, 5467]])
Targets are:
tensor([  24, 3565, 7696, 5467,  158, 3565,  883, 5467,   12, 3565,  883, 5467,
         158, 3565,  883, 1750])
Data is:
tensor([[ 158, 3565,  883, 1750],
        [8041, 3566,  872, 5468],
        [ 158, 3566,  872, 5468],
        [   2, 3566,  873, 1751]])
Targets are:
tensor([8041, 3566,  872,

Data is:
tensor([[6229, 7290,  724, 5535],
        [6229, 7290,  724, 5536],
        [6230, 3623,  725, 5536],
        [6230, 3623,  725, 5536]])
Targets are:
tensor([6229, 7290,  724, 5536, 6230, 3623,  725, 5536, 6230, 3623,  725, 5536,
        6231, 7291,  725, 5537])
Data is:
tensor([[6231, 7291,  725, 5537],
        [6231, 7291,  725, 5537],
        [6232, 7291,  725, 5537],
        [6232, 7292, 4569, 5538]])
Targets are:
tensor([6231, 7291,  725, 5537, 6232, 7291,  725, 5537, 6232, 7292, 4569, 5538,
        6232, 7292, 4570, 5538])
Data is:
tensor([[6232, 7292, 4570, 5538],
        [6232, 7292, 4570, 5538],
        [7815, 7292, 4570, 5538],
        [7816, 7293, 4570, 5539]])
Targets are:
tensor([6232, 7292, 4570, 5538, 7815, 7292, 4570, 5538, 7816, 7293, 4570, 5539,
        7816, 7293, 4571, 5539])
Data is:
tensor([[7816, 7293, 4571, 5539],
        [7816, 3624, 4571, 5539],
        [7816, 3624, 4571, 5539],
        [7816, 3624, 4572, 5540]])
Targets are:
tensor([7816, 3624, 4571,

Data is:
tensor([[6294, 3464, 4604, 5592],
        [6295, 7168, 4604, 5594],
        [6295, 7168, 4604, 5594],
        [6295, 3469, 4604, 5594]])
Targets are:
tensor([6295, 7168, 4604, 5594, 6295, 7168, 4604, 5594, 6295, 3469, 4604, 5594,
        6296, 3469, 4604, 5594])
Data is:
tensor([[6296, 3469, 4604, 5594],
        [6296, 3469, 4604, 5594],
        [6296, 3478, 4604, 5595],
        [6296, 3478, 4604, 5595]])
Targets are:
tensor([6296, 3469, 4604, 5594, 6296, 3478, 4604, 5595, 6296, 3478, 4604, 5595,
        6296, 3479, 4605, 5596])
Data is:
tensor([[6296, 3479, 4605, 5596],
        [6297, 3479, 4605, 5596],
        [6297, 3479, 4606, 5596],
        [6298, 3479, 4606, 1806]])
Targets are:
tensor([6297, 3479, 4605, 5596, 6297, 3479, 4606, 5596, 6298, 3479, 4606, 1806,
        6298, 3479, 4607, 5597])
Data is:
tensor([[6298, 3479, 4607, 5597],
        [6298, 3479, 4607, 5597],
        [6298, 3479, 4607, 5598],
        [6299, 3480, 4608, 5598]])
Targets are:
tensor([6298, 3479, 4607,

Data is:
tensor([[2202, 7208,  827, 1992],
        [2203, 7208, 4666, 1992],
        [2203, 7208, 4666, 1992],
        [2203, 7208, 4667, 1992]])
Targets are:
tensor([2203, 7208, 4666, 1992, 2203, 7208, 4666, 1992, 2203, 7208, 4667, 1992,
        2203, 7209, 4667, 1993])
Data is:
tensor([[2203, 7209, 4667, 1993],
        [6188, 7209, 4667, 1993],
        [6190, 7209, 4667, 1993],
        [6190, 7209, 4668, 5874]])
Targets are:
tensor([6188, 7209, 4667, 1993, 6190, 7209, 4667, 1993, 6190, 7209, 4668, 5874,
        6190, 7209, 4668, 5874])
Data is:
tensor([[6190, 7209, 4668, 5874],
        [6190, 7209, 4668, 5874],
        [6190, 7209, 4668, 5874],
        [6190, 7209, 4668, 5874]])
Targets are:
tensor([6190, 7209, 4668, 5874, 6190, 7209, 4668, 5874, 6190, 7209, 4668, 5874,
        6190, 7209, 4669, 5874])
Data is:
tensor([[6190, 7209, 4669, 5874],
        [6191, 3535, 4669, 1984],
        [6192, 7216, 4669, 1984],
        [6192, 7216,  829, 1984]])
Targets are:
tensor([6191, 3535, 4669,

Data is:
tensor([[2264, 7316, 1073, 5901],
        [2265, 7316, 1073, 5901],
        [2265, 7316, 1073, 2036],
        [2265, 7317, 4857, 2036]])
Targets are:
tensor([2265, 7316, 1073, 5901, 2265, 7316, 1073, 2036, 2265, 7317, 4857, 2036,
        2266, 7317, 4857, 2036])
Data is:
tensor([[2266, 7317, 4857, 2036],
        [2266, 7317, 4857, 2036],
        [7814, 7317, 1074, 2036],
        [7814, 7317, 1074, 5902]])
Targets are:
tensor([2266, 7317, 4857, 2036, 7814, 7317, 1074, 2036, 7814, 7317, 1074, 5902,
        7814, 7318, 4858, 5903])
Data is:
tensor([[7814, 7318, 4858, 5903],
        [7814, 7318, 4858, 5903],
        [7814, 7318, 4858, 1884],
        [7814, 7318, 4858, 1884]])
Targets are:
tensor([7814, 7318, 4858, 5903, 7814, 7318, 4858, 1884, 7814, 7318, 4858, 1884,
        7814, 7318, 1075, 1886])
Data is:
tensor([[7814, 7318, 1075, 1886],
        [2267, 7319, 1075, 1886],
        [2267, 7319, 1075, 1886],
        [2267, 7319, 1075, 1886]])
Targets are:
tensor([2267, 7319, 1075,

tensor([2317, 8000, 4880, 5751, 2318, 3810, 1125, 5752, 2318, 3810, 1125, 5739,
        2318, 3810, 1125, 5739])
Data is:
tensor([[2318, 3810, 1125, 5739],
        [2318, 3810, 1125, 5740],
        [2318, 3810, 4884, 5740],
        [2318, 3810, 4885, 5741]])
Targets are:
tensor([2318, 3810, 1125, 5740, 2318, 3810, 4884, 5740, 2318, 3810, 4885, 5741,
        2319, 3810, 4885, 5741])
Data is:
tensor([[2319, 3810, 4885, 5741],
        [2319, 3810, 1127, 5741],
        [6241, 3811, 1127, 5741],
        [6241, 3811, 1127, 5741]])
Targets are:
tensor([2319, 3810, 1127, 5741, 6241, 3811, 1127, 5741, 6241, 3811, 1127, 5741,
        6242, 3812, 1127, 5741])
Data is:
tensor([[6242, 3812, 1127, 5741],
        [6242, 3812, 4886, 5742],
        [6242, 3812, 4886, 5742],
        [6242, 3812, 1128, 5742]])
Targets are:
tensor([6242, 3812, 4886, 5742, 6242, 3812, 4886, 5742, 6242, 3812, 1128, 5742,
        2320, 3812, 1128, 5742])
Data is:
tensor([[2320, 3812, 1128, 5742],
        [2320, 3812, 4887, 1

Data is:
tensor([[2711, 3672,  975, 5806],
        [2711, 7975,  975, 1931],
        [6674, 3673, 7704, 1931],
        [6674, 3673, 7704, 1931]])
Targets are:
tensor([2711, 7975,  975, 1931, 6674, 3673, 7704, 1931, 6674, 3673, 7704, 1931,
        6674, 7971, 7704, 5807])
Data is:
tensor([[6674, 7971, 7704, 5807],
        [2718, 7971, 7704, 5807],
        [2718, 3663, 7704, 5808],
        [2718, 3663, 7704, 5808]])
Targets are:
tensor([2718, 7971, 7704, 5807, 2718, 3663, 7704, 5808, 2718, 3663, 7704, 5808,
        2718, 3663, 4745, 5808])
Data is:
tensor([[2718, 3663, 4745, 5808],
        [2718, 3663, 4745, 5808],
        [2718, 3666, 4745, 5808],
        [6675, 3666,  979, 5809]])
Targets are:
tensor([2718, 3663, 4745, 5808, 2718, 3666, 4745, 5808, 6675, 3666,  979, 5809,
        6675, 3667,  979, 5809])
Data is:
tensor([[6675, 3667,  979, 5809],
        [6675, 3667,  979, 5820],
        [6675, 3668,  979, 5820],
        [2719, 3668,  979, 5820]])
Targets are:
tensor([6675, 3667,  979,

Data is:
tensor([[2752, 7341, 4804, 2117],
        [2752, 7341, 4804, 7790],
        [2752, 7342, 4805, 2118],
        [6709, 7343, 4805, 2118]])
Targets are:
tensor([2752, 7341, 4804, 7790, 2752, 7342, 4805, 2118, 6709, 7343, 4805, 2118,
        6709, 7343, 4805, 2119])
Data is:
tensor([[6709, 7343, 4805, 2119],
        [6709, 7344, 1017, 6088],
        [6709, 7344, 1017, 2120],
        [6709, 7344, 4806, 2120]])
Targets are:
tensor([6709, 7344, 1017, 6088, 6709, 7344, 1017, 2120, 6709, 7344, 4806, 2120,
        2759, 7344, 4806, 2120])
Data is:
tensor([[2759, 7344, 4806, 2120],
        [2759, 7344, 4806, 6089],
        [2759, 7344, 4807, 2121],
        [2759, 7345, 4795, 2121]])
Targets are:
tensor([2759, 7344, 4806, 6089, 2759, 7344, 4807, 2121, 2759, 7345, 4795, 2121,
        2759, 7345, 4795, 2121])
Data is:
tensor([[2759, 7345, 4795, 2121],
        [6710, 7345, 4795, 6090],
        [6710, 7346, 4796, 6091],
        [2760, 3724, 4796, 6091]])
Targets are:
tensor([6710, 7345, 4795,

Data is:
tensor([[2585, 3758, 7722, 6129],
        [7841, 7377, 7722, 6129],
        [2593, 7377, 1231, 6129],
        [2593, 7378, 1232, 6129]])
Targets are:
tensor([7841, 7377, 7722, 6129, 2593, 7377, 1231, 6129, 2593, 7378, 1232, 6129,
        2593, 7378, 1232, 2158])
Data is:
tensor([[2593, 7378, 1232, 2158],
        [2593, 7378, 5015, 2158],
        [2594, 3767, 5015, 2158],
        [2594, 3767, 1234, 2158]])
Targets are:
tensor([2593, 7378, 5015, 2158, 2594, 3767, 5015, 2158, 2594, 3767, 1234, 2158,
        6592, 3767, 1234, 2158])
Data is:
tensor([[6592, 3767, 1234, 2158],
        [6592, 3769, 1223, 2158],
        [2595, 3769, 1223, 6130],
        [2595, 3769, 1223, 2159]])
Targets are:
tensor([6592, 3769, 1223, 2158, 2595, 3769, 1223, 6130, 2595, 3769, 1223, 2159,
        2596, 3769, 1223, 2159])
Data is:
tensor([[2596, 3769, 1223, 2159],
        [2596, 3769, 1223, 2159],
        [2596, 3769, 1223, 2159],
        [6594, 3769, 1224, 6131]])
Targets are:
tensor([2596, 3769, 1223,

tensor([[6615, 3988, 1275, 5934],
        [6615, 3988, 1275, 2061],
        [6615, 3989, 1275, 2061],
        [6615, 3989, 1275, 2061]])
Targets are:
tensor([6615, 3988, 1275, 2061, 6615, 3989, 1275, 2061, 6615, 3989, 1275, 2061,
        6615, 3989, 1275, 2061])
Data is:
tensor([[6615, 3989, 1275, 2061],
        [6615, 3989, 1275, 2061],
        [6615, 3990, 1275, 2061],
        [2647, 3992, 1275, 5935]])
Targets are:
tensor([6615, 3989, 1275, 2061, 6615, 3990, 1275, 2061, 2647, 3992, 1275, 5935,
        2647, 3992, 1283, 5935])
Data is:
tensor([[2647, 3992, 1283, 5935],
        [2647, 3992, 1283, 5936],
        [6616, 3992, 1283, 5936],
        [6616, 3992, 1284, 5937]])
Targets are:
tensor([2647, 3992, 1283, 5936, 6616, 3992, 1283, 5936, 6616, 3992, 1284, 5937,
        2640, 3993, 1284, 5937])
Data is:
tensor([[2640, 3993, 1284, 5937],
        [2640, 3993, 1285, 2066],
        [6607, 3993, 1285, 2066],
        [6607, 3993, 1285, 2066]])
Targets are:
tensor([2640, 3993, 1285, 2066, 66

Data is:
tensor([[2764, 7594, 5073, 5990],
        [2764, 4060, 5074, 5991],
        [2764, 4061, 5074, 5991],
        [2764, 4061, 5074, 5993]])
Targets are:
tensor([2764, 4060, 5074, 5991, 2764, 4061, 5074, 5991, 2764, 4061, 5074, 5993,
        2765, 4061, 5074, 5993])
Data is:
tensor([[2765, 4061, 5074, 5993],
        [2765, 4061, 1141, 5993],
        [2766, 4061, 1141, 5997],
        [2766, 4061, 1141, 5997]])
Targets are:
tensor([2765, 4061, 1141, 5993, 2766, 4061, 1141, 5997, 2766, 4061, 1141, 5997,
        2766, 4061, 1144, 5997])
Data is:
tensor([[2766, 4061, 1144, 5997],
        [2767, 4062, 1144, 5997],
        [2767, 4062, 1144, 5997],
        [2767, 4062, 1144, 5997]])
Targets are:
tensor([2767, 4062, 1144, 5997, 2767, 4062, 1144, 5997, 2767, 4062, 1144, 5997,
        2767, 4062, 1145, 6008])
Data is:
tensor([[2767, 4062, 1145, 6008],
        [2767, 4063, 1146, 6008],
        [6781, 4063, 1146, 6008],
        [6785, 4053, 1146, 6010]])
Targets are:
tensor([2767, 4063, 1146,

Data is:
tensor([[6838, 7472, 4927, 6078],
        [6838, 7472, 4927, 6078],
        [6838, 7472, 4928, 6078],
        [6838, 7473, 4928, 6078]])
Targets are:
tensor([6838, 7472, 4927, 6078, 6838, 7472, 4928, 6078, 6838, 7473, 4928, 6078,
        6839, 7473, 4929, 6078])
Data is:
tensor([[6839, 7473, 4929, 6078],
        [6839, 7473, 4929, 6080],
        [6839, 7473, 4930, 6080],
        [6840, 7473, 4930, 6080]])
Targets are:
tensor([6839, 7473, 4929, 6080, 6839, 7473, 4930, 6080, 6840, 7473, 4930, 6080,
        6840, 7473, 4930, 6080])
Data is:
tensor([[6840, 7473, 4930, 6080],
        [7891, 3897, 4930, 6080],
        [7891, 3897, 4933, 6080],
        [7891, 3897, 4933, 6081]])
Targets are:
tensor([7891, 3897, 4930, 6080, 7891, 3897, 4933, 6080, 7891, 3897, 4933, 6081,
        2932, 3897, 4936, 6081])
Data is:
tensor([[2932, 3897, 4936, 6081],
        [2932, 3897, 7720, 6081],
        [6832, 7474, 7720, 6081],
        [2933, 7474, 1190, 6082]])
Targets are:
tensor([2932, 3897, 7720,

Data is:
tensor([[7862, 7495, 1218, 2477],
        [7863, 7495, 1218, 2477],
        [7863, 7495, 4988, 2482],
        [7863, 7496, 4988, 2482]])
Targets are:
tensor([7863, 7495, 1218, 2477, 7863, 7495, 4988, 2482, 7863, 7496, 4988, 2482,
        2779, 7496, 4988, 2482])
Data is:
tensor([[2779, 7496, 4988, 2482],
        [6725, 3939, 4989, 2482],
        [2768, 3939, 4989, 2484],
        [2768, 3939, 4989, 2485]])
Targets are:
tensor([6725, 3939, 4989, 2482, 2768, 3939, 4989, 2484, 2768, 3939, 4989, 2485,
        2768, 3939, 4989, 2485])
Data is:
tensor([[2768, 3939, 4989, 2485],
        [2768, 3939, 4989, 2485],
        [2768, 7504, 1219, 2485],
        [2769, 7504, 1220, 2485]])
Targets are:
tensor([2768, 3939, 4989, 2485, 2768, 7504, 1219, 2485, 2769, 7504, 1220, 2485,
        2769, 3940, 1220, 2486])
Data is:
tensor([[2769, 3940, 1220, 2486],
        [2769, 7505, 1220, 2486],
        [2769, 7505, 4990, 2487],
        [2769, 7505, 4990, 2487]])
Targets are:
tensor([2769, 7505, 1220,

Data is:
tensor([[2818, 8024, 1466, 2525],
        [2819, 8024, 1466, 6535],
        [2819, 3982, 1451, 6535],
        [2819, 3982, 1451, 6535]])
Targets are:
tensor([2819, 8024, 1466, 6535, 2819, 3982, 1451, 6535, 2819, 3982, 1451, 6535,
        2820, 3982, 1452, 6535])
Data is:
tensor([[2820, 3982, 1452, 6535],
        [2820, 3982, 1452, 6535],
        [2820, 3982, 1453, 6536],
        [2820, 3982, 1453, 6536]])
Targets are:
tensor([2820, 3982, 1452, 6535, 2820, 3982, 1453, 6536, 2820, 3982, 1453, 6536,
        7873, 3982, 1453, 6536])
Data is:
tensor([[7873, 3982, 1453, 6536],
        [2821, 3982, 1453, 6536],
        [2821, 7544, 1453, 6536],
        [2821, 7544, 1454, 6537]])
Targets are:
tensor([2821, 3982, 1453, 6536, 2821, 7544, 1453, 6536, 2821, 7544, 1454, 6537,
        2822, 7544, 1454, 6537])
Data is:
tensor([[2822, 7544, 1454, 6537],
        [2822, 7544, 1454, 6537],
        [2822, 7545, 1455, 6537],
        [2822, 7545, 1455, 6537]])
Targets are:
tensor([2822, 7544, 1454,

Data is:
tensor([[2870, 4360, 1532, 6343],
        [2870, 4360, 1533, 2418],
        [2870, 4360, 1533, 2418],
        [2870, 4360, 1533, 2418]])
Targets are:
tensor([2870, 4360, 1533, 2418, 2870, 4360, 1533, 2418, 2870, 4360, 1533, 2418,
        2870, 4360, 1534, 2418])
Data is:
tensor([[2870, 4360, 1534, 2418],
        [2870, 4361, 1534, 2418],
        [2870, 4361, 1534, 6344],
        [2870, 4361, 1534, 6344]])
Targets are:
tensor([2870, 4361, 1534, 2418, 2870, 4361, 1534, 6344, 2870, 4361, 1534, 6344,
        6765,  400, 1535, 6344])
Data is:
tensor([[6765,  400, 1535, 6344],
        [6766,  400, 1535, 6344],
        [6767,  400, 1536, 6344],
        [6767, 4362, 1536, 6345]])
Targets are:
tensor([6766,  400, 1535, 6344, 6767,  400, 1536, 6344, 6767, 4362, 1536, 6345,
        6768, 4362, 1536, 6346])
Data is:
tensor([[6768, 4362, 1536, 6346],
        [6768, 4362, 1536, 6346],
        [6768, 4362, 1537, 6347],
        [6768, 4362, 1537, 6347]])
Targets are:
tensor([6768, 4362, 1536,

Data is:
tensor([[3104, 7653, 1351, 6436],
        [3105, 7653, 1351, 6436],
        [3105,  450, 1353, 6437],
        [3105,  451, 1353, 6437]])
Targets are:
tensor([3105, 7653, 1351, 6436, 3105,  450, 1353, 6437, 3105,  451, 1353, 6437,
        3105,  451, 1353, 6437])
Data is:
tensor([[3105,  451, 1353, 6437],
        [3106,  451, 1353, 6437],
        [3107,  452, 1353, 6438],
        [3107,  452, 5086, 6438]])
Targets are:
tensor([3106,  451, 1353, 6437, 3107,  452, 1353, 6438, 3107,  452, 5086, 6438,
        3107,  453, 5086, 6438])
Data is:
tensor([[3107,  453, 5086, 6438],
        [3122,  453, 5086, 6439],
        [3122, 7654, 1343, 6439],
        [3122, 7654, 1343, 6440]])
Targets are:
tensor([3122,  453, 5086, 6439, 3122, 7654, 1343, 6439, 3122, 7654, 1343, 6440,
        6959, 7654, 1343, 6440])
Data is:
tensor([[6959, 7654, 1343, 6440],
        [6959, 7654, 1343, 6441],
        [3128,  454, 1344, 6423],
        [6961,  454, 1344, 6424]])
Targets are:
tensor([6959, 7654, 1343,

Data is:
tensor([[6984, 4260, 5109, 2454],
        [6985, 4261, 1376, 2454],
        [6986, 4261, 1376, 2454],
        [6986, 4261, 1376, 2455]])
Targets are:
tensor([6985, 4261, 1376, 2454, 6986, 4261, 1376, 2454, 6986, 4261, 1376, 2455,
        6986, 4261, 1376, 2455])
Data is:
tensor([[6986, 4261, 1376, 2455],
        [6986, 4261, 1376, 6487],
        [6986, 4262, 5110, 6487],
        [6986, 4263, 5110, 6488]])
Targets are:
tensor([6986, 4261, 1376, 6487, 6986, 4262, 5110, 6487, 6986, 4263, 5110, 6488,
        6986, 4263, 1377, 6488])
Data is:
tensor([[6986, 4263, 1377, 6488],
        [6987, 4263, 1377, 2456],
        [7923, 4263, 5111, 2456],
        [7923, 7643, 5111, 2456]])
Targets are:
tensor([6987, 4263, 1377, 2456, 7923, 4263, 5111, 2456, 7923, 7643, 5111, 2456,
        7924, 7643, 5111, 6489])
Data is:
tensor([[7924, 7643, 5111, 6489],
        [7924, 7643, 1378, 6490],
        [3152, 7643, 1378, 6490],
        [3152, 7643, 1380, 6490]])
Targets are:
tensor([7924, 7643, 1378,

Data is:
tensor([[7628, 7000,  296, 1422],
        [   4, 7000,  296, 1422],
        [ 162, 7001,  296, 5134],
        [   0, 7001, 4279, 5134]])
Targets are:
tensor([   4, 7000,  296, 1422,  162, 7001,  296, 5134,    0, 7001, 4279, 5134,
         162, 7001, 4279, 1412])
Data is:
tensor([[ 162, 7001, 4279, 1412],
        [   5, 7001, 4279, 1412],
        [ 163, 7001, 4279, 1412],
        [   9, 3181, 4279, 5127]])
Targets are:
tensor([   5, 7001, 4279, 1412,  163, 7001, 4279, 1412,    9, 3181, 4279, 5127,
         164, 3181, 4279, 5127])
Data is:
tensor([[ 164, 3181, 4279, 5127],
        [   1, 3181, 4280, 5128],
        [ 164, 7926, 4280, 5128],
        [  10, 3182, 4280, 5128]])
Targets are:
tensor([   1, 3181, 4280, 5128,  164, 7926, 4280, 5128,   10, 3182, 4280, 5128,
         164, 3182, 4281, 5129])
Data is:
tensor([[ 164, 3182, 4281, 5129],
        [   3, 3182, 4281, 5130],
        [ 164, 7002, 4281, 1413],
        [  13, 7002, 4281, 1413]])
Targets are:
tensor([   3, 3182, 4281,

tensor([[ 196, 3008,  353, 7749],
        [   5, 3008,  353, 1580],
        [4209, 3009,  353, 1580],
        [  16, 3009,  354, 1581]])
Targets are:
tensor([   5, 3008,  353, 1580, 4209, 3009,  353, 1580,   16, 3009,  354, 1581,
         203, 3009,  354, 1581])
Data is:
tensor([[ 203, 3009,  354, 1581],
        [  15, 6883,  354, 1581],
        [ 203, 6883,  354, 1581],
        [8048, 6883,  354, 1582]])
Targets are:
tensor([  15, 6883,  354, 1581,  203, 6883,  354, 1581, 8048, 6883,  354, 1582,
         203, 3010,  355, 1582])
Data is:
tensor([[ 203, 3010,  355, 1582],
        [8043, 3010,  355, 7750],
        [4210, 3010, 4330, 7750],
        [8048, 6884, 4330, 7750]])
Targets are:
tensor([8043, 3010,  355, 7750, 4210, 3010, 4330, 7750, 8048, 6884, 4330, 7750,
        4210, 6884, 4331, 7750])
Data is:
tensor([[4210, 6884, 4331, 7750],
        [   5, 6884, 4331, 1583],
        [4210, 6884, 4331, 1583],
        [   4, 6884, 4331, 1583]])
Targets are:
tensor([   5, 6884, 4331, 1583, 42

Data is:
tensor([[ 212, 3070, 4390, 5391],
        [   0, 3070, 4390, 5391],
        [ 212, 3070, 4390, 5392],
        [   0, 3070,  491, 5392]])
Targets are:
tensor([   0, 3070, 4390, 5391,  212, 3070, 4390, 5392,    0, 3070,  491, 5392,
         212, 6904,  491, 5392])
Data is:
tensor([[ 212, 6904,  491, 5392],
        [   1, 6904,  491, 5392],
        [ 214, 6904, 4391, 5393],
        [  21, 3058, 4391, 5393]])
Targets are:
tensor([   1, 6904,  491, 5392,  214, 6904, 4391, 5393,   21, 3058, 4391, 5393,
         214, 3058, 4391, 5393])
Data is:
tensor([[ 214, 3058, 4391, 5393],
        [  15, 3058, 4391, 1674],
        [ 214, 3059,  492, 1674],
        [   8, 3059,  492, 1674]])
Targets are:
tensor([  15, 3058, 4391, 1674,  214, 3059,  492, 1674,    8, 3059,  492, 1674,
         214, 3059,  492, 1674])
Data is:
tensor([[ 214, 3059,  492, 1674],
        [   4, 6905,  492, 1674],
        [ 214, 6906, 4392, 1679],
        [   7, 3060, 4392, 1680]])
Targets are:
tensor([   4, 6905,  492,

Data is:
tensor([[ 230, 6934, 4521, 1710],
        [  17, 6934, 4521, 1711],
        [ 230, 6934,  632, 1711],
        [  20, 6935,  632, 1711]])
Targets are:
tensor([  17, 6934, 4521, 1711,  230, 6934,  632, 1711,   20, 6935,  632, 1711,
         230, 6935,  632, 1711])
Data is:
tensor([[ 230, 6935,  632, 1711],
        [   5, 6935,  632, 1711],
        [ 230, 6935,  632, 1712],
        [  15, 3108,  632, 1712]])
Targets are:
tensor([   5, 6935,  632, 1711,  230, 6935,  632, 1712,   15, 3108,  632, 1712,
         230, 3115,  638, 1712])
Data is:
tensor([[ 230, 3115,  638, 1712],
        [   5, 3115,  638, 1712],
        [ 231, 3115,  638, 1712],
        [   7, 3115, 7673, 1713]])
Targets are:
tensor([   5, 3115,  638, 1712,  231, 3115,  638, 1712,    7, 3115, 7673, 1713,
         231, 3115, 7673, 1713])
Data is:
tensor([[ 231, 3115, 7673, 1713],
        [   2, 3115, 4527, 1713],
        [ 231, 3116,  646, 1713],
        [  36, 3117,  646, 1714]])
Targets are:
tensor([   2, 3115, 4527,

Data is:
tensor([[  68, 3380, 4551, 5247],
        [   0, 3380, 4551, 5248],
        [4108, 7939,  695, 5248],
        [  26, 7939, 4552, 5248]])
Targets are:
tensor([   0, 3380, 4551, 5248, 4108, 7939,  695, 5248,   26, 7939, 4552, 5248,
        4108, 7939, 4552, 5249])
Data is:
tensor([[4108, 7939, 4552, 5249],
        [  24, 7939, 4552, 5249],
        [4108, 3371, 4552, 5249],
        [   7, 7105,  696, 5249]])
Targets are:
tensor([  24, 7939, 4552, 5249, 4108, 3371, 4552, 5249,    7, 7105,  696, 5249,
        4108, 7105,  696, 5250])
Data is:
tensor([[4108, 7105,  696, 5250],
        [   0, 3372,  696, 5250],
        [  69, 3372,  696, 5250],
        [   4, 3373, 4553, 5250]])
Targets are:
tensor([   0, 3372,  696, 5250,   69, 3372,  696, 5250,    4, 3373, 4553, 5250,
          69, 3373, 4553, 5250])
Data is:
tensor([[  69, 3373, 4553, 5250],
        [  30, 3373, 4553, 5250],
        [  69, 3373, 4553, 5250],
        [   7, 7106, 4553, 5251]])
Targets are:
tensor([  30, 3373, 4553,

Data is:
tensor([[  80, 3406, 4421, 7752],
        [   6, 3406, 4422, 7752],
        [  83, 3406, 4422, 7752],
        [   7, 3406, 4422, 5297]])
Targets are:
tensor([   6, 3406, 4422, 7752,   83, 3406, 4422, 7752,    7, 3406, 4422, 5297,
          83, 3407, 4423, 5297])
Data is:
tensor([[  83, 3407, 4423, 5297],
        [  19, 3408, 4423, 5297],
        [  83, 3408, 4423, 5298],
        [   7, 3408,  535, 5298]])
Targets are:
tensor([  19, 3408, 4423, 5297,   83, 3408, 4423, 5298,    7, 3408,  535, 5298,
          83, 3409,  535, 5298])
Data is:
tensor([[  83, 3409,  535, 5298],
        [   0, 3409,  535, 5299],
        [4120, 3409,  535, 5299],
        [   2, 3410, 4424, 5299]])
Targets are:
tensor([   0, 3409,  535, 5299, 4120, 3409,  535, 5299,    2, 3410, 4424, 5299,
        4120, 3410,  536, 5299])
Data is:
tensor([[4120, 3410,  536, 5299],
        [  17, 7137,  536, 5300],
        [4120, 7137, 4425, 5300],
        [   7, 7137,  537, 5300]])
Targets are:
tensor([  17, 7137,  536,

Data is:
tensor([[ 115, 7936,  583, 5443],
        [   1, 3241,  583, 5443],
        [ 115, 3230,  583, 1730],
        [   1, 3230,  583, 1730]])
Targets are:
tensor([   1, 3241,  583, 5443,  115, 3230,  583, 1730,    1, 3230,  583, 1730,
         115, 3231, 4482, 1730])
Data is:
tensor([[ 115, 3231, 4482, 1730],
        [   3, 3231, 4482, 1730],
        [ 115, 3231, 4482, 5434],
        [  32, 7030, 4482, 5434]])
Targets are:
tensor([   3, 3231, 4482, 1730,  115, 3231, 4482, 5434,   32, 7030, 4482, 5434,
         115, 7030, 4483, 5434])
Data is:
tensor([[ 115, 7030, 4483, 5434],
        [   4, 7030,  584, 1731],
        [ 116, 7030,  584, 1731],
        [  10, 3232, 4472, 1731]])
Targets are:
tensor([   4, 7030,  584, 1731,  116, 7030,  584, 1731,   10, 3232, 4472, 1731,
         116, 3232, 4472, 1731])
Data is:
tensor([[ 116, 3232, 4472, 1731],
        [  19, 3232, 4472, 5435],
        [ 116, 3232, 4472, 5435],
        [   1, 3233, 4472, 5435]])
Targets are:
tensor([  19, 3232, 4472,

tensor([[ 132, 3310, 4679, 5654],
        [   5, 3310, 4679, 5654],
        [7625, 3310, 4681, 5654],
        [   5, 3311, 4681, 5654]])
Targets are:
tensor([   5, 3310, 4679, 5654, 7625, 3310, 4681, 5654,    5, 3311, 4681, 5654,
        7625, 3311, 4681, 5654])
Data is:
tensor([[7625, 3311, 4681, 5654],
        [   9, 3311, 4682, 5654],
        [4142, 3311, 4682, 1850],
        [   6, 3311, 4682, 1850]])
Targets are:
tensor([   9, 3311, 4682, 5654, 4142, 3311, 4682, 1850,    6, 3311, 4682, 1850,
        4142, 3311, 4682, 1850])
Data is:
tensor([[4142, 3311, 4682, 1850],
        [   7, 3312, 4683, 5655],
        [4143, 3312, 4683, 5655],
        [   3, 3313, 4683, 5655]])
Targets are:
tensor([   7, 3312, 4683, 5655, 4143, 3312, 4683, 5655,    3, 3313, 4683, 5655,
        4143, 3313, 7689, 5655])
Data is:
tensor([[4143, 3313, 7689, 5655],
        [   3, 3313, 7689, 1851],
        [4143, 3313, 7689, 1851],
        [   4, 3313, 4684, 1851]])
Targets are:
tensor([   3, 3313, 7689, 1851, 41

Data is:
tensor([[ 173, 7242,  906, 5480],
        [  25, 7242,  906, 5480],
        [ 174, 7244,  906, 5480],
        [   6, 7957,  906, 5481]])
Targets are:
tensor([  25, 7242,  906, 5480,  174, 7244,  906, 5480,    6, 7957,  906, 5481,
         174, 7957,  906, 5481])
Data is:
tensor([[ 174, 7957,  906, 5481],
        [  12, 7957, 4697, 5481],
        [ 174, 7956, 4697, 5482],
        [  12, 3562,  907, 5482]])
Targets are:
tensor([  12, 7957, 4697, 5481,  174, 7956, 4697, 5482,   12, 3562,  907, 5482,
         175, 3562,  907, 5482])
Data is:
tensor([[ 175, 3562,  907, 5482],
        [  10, 3562,  907, 5469],
        [ 175, 3562,  907, 5469],
        [   6, 3562, 4698, 5469]])
Targets are:
tensor([  10, 3562,  907, 5469,  175, 3562,  907, 5469,    6, 3562, 4698, 5469,
         175, 3563, 4698, 5470])
Data is:
tensor([[ 175, 3563, 4698, 5470],
        [  28, 3563, 4698, 5470],
        [ 175, 3564, 4698, 5470],
        [   3, 3564, 4698, 1753]])
Targets are:
tensor([  28, 3563, 4698,

Data is:
tensor([[6267, 7292, 4587, 1780],
        [6268, 7292, 4588, 1780],
        [6268, 7293, 4588, 1780],
        [6268, 7293, 4588, 5551]])
Targets are:
tensor([6268, 7292, 4588, 1780, 6268, 7293, 4588, 1780, 6268, 7293, 4588, 5551,
        6269, 7293, 4589, 5551])
Data is:
tensor([[6269, 7293, 4589, 5551],
        [6269, 7293, 4589, 1781],
        [6270, 3624, 4589, 1781],
        [6270, 3624, 4590, 1781]])
Targets are:
tensor([6269, 7293, 4589, 1781, 6270, 3624, 4589, 1781, 6270, 3624, 4590, 1781,
        6270, 3624, 4590, 1781])
Data is:
tensor([[6270, 3624, 4590, 1781],
        [6270, 7294, 4590, 5552],
        [6260, 7294, 4590, 5552],
        [6260, 7294, 4590, 5552]])
Targets are:
tensor([6270, 7294, 4590, 5552, 6260, 7294, 4590, 5552, 6260, 7294, 4590, 5552,
        6260, 3625, 4591, 1774])
Data is:
tensor([[6260, 3625, 4591, 1774],
        [6260, 3625, 4591, 1774],
        [6260, 3625, 4591, 1774],
        [6260, 3625, 4591, 5543]])
Targets are:
tensor([6260, 3625, 4591,

Data is:
tensor([[2375, 3474,  806, 5831],
        [2375, 3474,  806, 5831],
        [2375, 3474,  806, 5831],
        [2376, 3475,  806, 5831]])
Targets are:
tensor([2375, 3474,  806, 5831, 2375, 3474,  806, 5831, 2376, 3475,  806, 5831,
        2376, 3475,  806, 5832])
Data is:
tensor([[2376, 3475,  806, 5832],
        [2376, 3476,  807, 1956],
        [2377, 3476,  807, 1956],
        [2377, 3476,  807, 1956]])
Targets are:
tensor([2376, 3476,  807, 1956, 2377, 3476,  807, 1956, 2377, 3476,  807, 1956,
        2377, 3476,  807, 1964])
Data is:
tensor([[2377, 3476,  807, 1964],
        [2377, 7173, 4632, 1964],
        [2377, 7173, 4633, 1964],
        [2378, 3477, 4633, 1965]])
Targets are:
tensor([2377, 7173, 4632, 1964, 2377, 7173, 4633, 1964, 2378, 3477, 4633, 1965,
        2378, 3477, 4633, 1965])
Data is:
tensor([[2378, 3477, 4633, 1965],
        [2379, 3477,  798, 1965],
        [2379, 3477, 4634, 1965],
        [2379, 3477, 4634, 1966]])
Targets are:
tensor([2379, 3477,  798,

Data is:
tensor([[2232, 3531, 1053, 5884],
        [2232, 3532, 1053, 5884],
        [2232, 3533, 4846, 5885],
        [2232, 3533, 1043, 5885]])
Targets are:
tensor([2232, 3532, 1053, 5884, 2232, 3533, 4846, 5885, 2232, 3533, 1043, 5885,
        2232, 3533, 1043, 5885])
Data is:
tensor([[2232, 3533, 1043, 5885],
        [2233, 3533, 4841, 5885],
        [2233, 7212, 4841, 5885],
        [2233, 7212, 4841, 5886]])
Targets are:
tensor([2233, 3533, 4841, 5885, 2233, 7212, 4841, 5885, 2233, 7212, 4841, 5886,
        2233, 7212, 4841, 5886])
Data is:
tensor([[2233, 7212, 4841, 5886],
        [2233, 7212, 4841, 5886],
        [2234, 7212, 1044, 5886],
        [2234, 7213, 1044, 5886]])
Targets are:
tensor([2233, 7212, 4841, 5886, 2234, 7212, 1044, 5886, 2234, 7213, 1044, 5886,
        2234, 7213, 1044, 5887])
Data is:
tensor([[2234, 7213, 1044, 5887],
        [2235, 7214, 1044, 5887],
        [2235, 3534, 1044, 5887],
        [2235, 3534, 1045, 5887]])
Targets are:
tensor([2235, 7214, 1044,

Data is:
tensor([[2300, 3778, 1115, 5718],
        [2300, 3778, 1115, 5718],
        [2301, 3779, 1115, 5718],
        [2301, 3779, 1115, 5719]])
Targets are:
tensor([2300, 3778, 1115, 5718, 2301, 3779, 1115, 5718, 2301, 3779, 1115, 5719,
        2301, 3779, 1116, 5719])
Data is:
tensor([[2301, 3779, 1116, 5719],
        [2301, 3779, 1116, 5719],
        [2301, 3779, 1117, 5720],
        [2301, 3779, 1117, 5720]])
Targets are:
tensor([2301, 3779, 1116, 5719, 2301, 3779, 1117, 5720, 2301, 3779, 1117, 5720,
        2302, 3780, 1117, 5721])
Data is:
tensor([[2302, 3780, 1117, 5721],
        [2302, 3780, 1117, 5721],
        [6220, 3780, 1105, 5721],
        [6220, 3780, 1105, 5721]])
Targets are:
tensor([2302, 3780, 1117, 5721, 6220, 3780, 1105, 5721, 6220, 3780, 1105, 5721,
        6220, 3780, 1105, 5721])
Data is:
tensor([[6220, 3780, 1105, 5721],
        [6222, 3781, 1105, 5722],
        [6222, 3781, 1106, 1905],
        [6222, 3781, 1106, 1905]])
Targets are:
tensor([6222, 3781, 1105,

Data is:
tensor([[7853, 7437, 7705, 1924],
        [7853, 7437, 7705, 1932],
        [6660, 7437, 7705, 1933],
        [6660, 7437, 4746, 1934]])
Targets are:
tensor([7853, 7437, 7705, 1932, 6660, 7437, 7705, 1933, 6660, 7437, 4746, 1934,
        2703, 7437, 4746, 1934])
Data is:
tensor([[2703, 7437, 4746, 1934],
        [2703, 7437, 4746, 1935],
        [2703, 7437,  977, 1935],
        [2704, 7439,  977, 1936]])
Targets are:
tensor([2703, 7437, 4746, 1935, 2703, 7437,  977, 1935, 2704, 7439,  977, 1936,
        2704, 7439,  977, 1936])
Data is:
tensor([[2704, 7439,  977, 1936],
        [2704, 7439,  977, 1936],
        [2705, 7440, 4747, 1937],
        [2705, 7440, 4747, 1937]])
Targets are:
tensor([2704, 7439,  977, 1936, 2705, 7440, 4747, 1937, 2705, 7440, 4747, 1937,
        2706, 7441, 4747, 1938])
Data is:
tensor([[2706, 7441, 4747, 1938],
        [2706, 7441, 4747, 1938],
        [2707, 7441, 4748, 1938],
        [2707, 7442, 4748, 1939]])
Targets are:
tensor([2706, 7441, 4747,

Data is:
tensor([[6704, 3707, 4805, 6095],
        [6704, 3708, 4805, 6095],
        [6704, 3708, 1017, 2125],
        [6704, 3708, 1017, 6096]])
Targets are:
tensor([6704, 3708, 4805, 6095, 6704, 3708, 1017, 2125, 6704, 3708, 1017, 6096,
        6704, 3709, 1017, 2117])
Data is:
tensor([[6704, 3709, 1017, 2117],
        [2754, 3710, 4806, 2117],
        [2754, 3710, 4806, 7790],
        [2754, 3710, 4806, 7790]])
Targets are:
tensor([2754, 3710, 4806, 2117, 2754, 3710, 4806, 7790, 2754, 3710, 4806, 7790,
        2754, 3710, 4806, 2118])
Data is:
tensor([[2754, 3710, 4806, 2118],
        [2754, 3699, 4806, 2119],
        [6705, 3700, 4807, 2119],
        [6705, 3700, 4807, 2119]])
Targets are:
tensor([2754, 3699, 4806, 2119, 6705, 3700, 4807, 2119, 6705, 3700, 4807, 2119,
        6705, 3700, 4807, 2119])
Data is:
tensor([[6705, 3700, 4807, 2119],
        [6705, 3700, 4807, 6088],
        [2755, 3700, 4807, 6088],
        [2755, 3701, 4807, 2120]])
Targets are:
tensor([6705, 3700, 4807,

Data is:
tensor([[2604, 7375, 1244, 2170],
        [2605, 7376, 1244, 6150],
        [2605, 7376, 1245, 6150],
        [2605, 7376, 1245, 6138]])
Targets are:
tensor([2605, 7376, 1244, 6150, 2605, 7376, 1245, 6150, 2605, 7376, 1245, 6138,
        2605, 3758, 1245, 6138])
Data is:
tensor([[2605, 3758, 1245, 6138],
        [2606, 3758, 1245, 6139],
        [2606, 3758, 1246, 6139],
        [2607, 3758, 1247, 6139]])
Targets are:
tensor([2606, 3758, 1245, 6139, 2606, 3758, 1246, 6139, 2607, 3758, 1247, 6139,
        7845, 3758, 1247, 6140])
Data is:
tensor([[7845, 3758, 1247, 6140],
        [7845, 7377, 1247, 6141],
        [7845, 7377, 1247, 6141],
        [7845, 7377, 1247, 6142]])
Targets are:
tensor([7845, 7377, 1247, 6141, 7845, 7377, 1247, 6141, 7845, 7377, 1247, 6142,
        2608, 7378, 1248, 6142])
Data is:
tensor([[2608, 7378, 1248, 6142],
        [2608, 7378, 1248, 6142],
        [2609, 7378, 1248, 6142],
        [2609, 3767, 1248, 6143]])
Targets are:
tensor([2608, 7378, 1248,

Data is:
tensor([[6620, 4004, 1297, 2072],
        [6620, 7564, 1297, 2072],
        [6620, 4005, 5057, 5956],
        [6620, 4005, 5057, 5956]])
Targets are:
tensor([6620, 7564, 1297, 2072, 6620, 4005, 5057, 5956, 6620, 4005, 5057, 5956,
        6621, 7565, 5057, 5956])
Data is:
tensor([[6621, 7565, 5057, 5956],
        [6621, 7565, 5057, 5956],
        [6621, 4006, 5059, 5956],
        [6621, 4006, 5059, 5956]])
Targets are:
tensor([6621, 7565, 5057, 5956, 6621, 4006, 5059, 5956, 6621, 4006, 5059, 5956,
        6621, 4006, 5059, 5956])
Data is:
tensor([[6621, 4006, 5059, 5956],
        [6621, 4006, 1302, 5956],
        [6621, 4006, 1302, 7788],
        [6621, 4006, 1302, 7788]])
Targets are:
tensor([6621, 4006, 1302, 5956, 6621, 4006, 1302, 7788, 6621, 4006, 1302, 7788,
        2669, 7566, 1308, 7788])
Data is:
tensor([[2669, 7566, 1308, 7788],
        [2669, 7566, 1308, 2073],
        [2669, 7566, 1308, 2073],
        [2669, 4007, 1309, 2073]])
Targets are:
tensor([2669, 7566, 1308,

Data is:
tensor([[2913, 4076, 1164, 6048],
        [2913, 4076, 1164, 6048],
        [2913, 4076, 4916, 2101],
        [2914, 7604, 4917, 6055]])
Targets are:
tensor([2913, 4076, 1164, 6048, 2913, 4076, 4916, 2101, 2914, 7604, 4917, 6055,
        2914, 7604, 4917, 6055])
Data is:
tensor([[2914, 7604, 4917, 6055],
        [2914, 7604, 4917, 6055],
        [2915, 7604, 4917, 2102],
        [2915, 4083, 4918, 2102]])
Targets are:
tensor([2914, 7604, 4917, 6055, 2915, 7604, 4917, 2102, 2915, 4083, 4918, 2102,
        2915, 4083, 4918, 2102])
Data is:
tensor([[2915, 4083, 4918, 2102],
        [2915, 4083, 4919, 6056],
        [2916, 7605, 4919, 6056],
        [2916, 4084, 4919, 6056]])
Targets are:
tensor([2915, 4083, 4919, 6056, 2916, 7605, 4919, 6056, 2916, 4084, 4919, 6056,
        2916, 4084, 4919, 2103])
Data is:
tensor([[2916, 4084, 4919, 2103],
        [2916, 4084, 4920, 2103],
        [2916, 4084, 4920, 6057],
        [2916, 7606, 4920, 6057]])
Targets are:
tensor([2916, 4084, 4920,

Data is:
tensor([[6850, 8021, 4957, 6497],
        [6850, 8021, 4958, 6498],
        [6850, 3915, 4958, 6498],
        [6851, 3915, 4958, 6498]])
Targets are:
tensor([6850, 8021, 4958, 6498, 6850, 3915, 4958, 6498, 6851, 3915, 4958, 6498,
        6851, 7480, 1211, 6498])
Data is:
tensor([[6851, 7480, 1211, 6498],
        [6851, 7481, 1211, 6498],
        [6851, 7481, 1211, 6499],
        [6852, 7481, 1211, 6500]])
Targets are:
tensor([6851, 7481, 1211, 6498, 6851, 7481, 1211, 6499, 6852, 7481, 1211, 6500,
        6852, 7481, 1213, 6500])
Data is:
tensor([[6852, 7481, 1213, 6500],
        [6852, 3916, 1213, 6500],
        [6852, 3916, 1213, 2477],
        [6852, 7482, 1213, 2477]])
Targets are:
tensor([6852, 3916, 1213, 6500, 6852, 3916, 1213, 2477, 6852, 7482, 1213, 2477,
        6852, 7482, 1213, 2477])
Data is:
tensor([[6852, 7482, 1213, 2477],
        [6853, 7482, 1213, 2477],
        [6853, 7482, 4972, 2477],
        [6853, 3917, 4972, 2482]])
Targets are:
tensor([6853, 7482, 1213,

Data is:
tensor([[2812, 3966, 1463, 6542],
        [2812, 3966, 1463, 6543],
        [2813, 3966, 1464, 6543],
        [2813, 3966, 1464, 6543]])
Targets are:
tensor([2812, 3966, 1463, 6543, 2813, 3966, 1464, 6543, 2813, 3966, 1464, 6543,
        2814, 7533, 1464, 2533])
Data is:
tensor([[2814, 7533, 1464, 2533],
        [2814, 7534, 1464, 2533],
        [2815, 7535, 1464, 2533],
        [2815, 7535, 1465, 2535]])
Targets are:
tensor([2814, 7534, 1464, 2533, 2815, 7535, 1464, 2533, 2815, 7535, 1465, 2535,
        2816, 7535, 1465, 2535])
Data is:
tensor([[2816, 7535, 1465, 2535],
        [2816, 7535, 1466, 2535],
        [2805, 3979, 1466, 2535],
        [2805, 3979, 1466, 2535]])
Targets are:
tensor([2816, 7535, 1466, 2535, 2805, 3979, 1466, 2535, 2805, 3979, 1466, 2535,
        2805, 7543, 1466, 2536])
Data is:
tensor([[2805, 7543, 1466, 2536],
        [2805, 7543, 1466, 2536],
        [2806, 7543, 1466, 2536],
        [2806, 3980, 1451, 2536]])
Targets are:
tensor([2805, 7543, 1466,

Data is:
tensor([[2876, 4365, 5196, 6387],
        [2877, 4365, 5196, 6387],
        [2877, 4365, 1546, 6387],
        [2877, 4365, 5197, 6388]])
Targets are:
tensor([2877, 4365, 5196, 6387, 2877, 4365, 1546, 6387, 2877, 4365, 5197, 6388,
        2877, 4366, 5197, 6389])
Data is:
tensor([[2877, 4366, 5197, 6389],
        [2877, 4366, 5197, 6389],
        [2878, 4367, 5197, 6389],
        [2878, 4367, 5197, 6389]])
Targets are:
tensor([2877, 4366, 5197, 6389, 2878, 4367, 5197, 6389, 2878, 4367, 5197, 6389,
        2879, 4367, 1547, 6390])
Data is:
tensor([[2879, 4367, 1547, 6390],
        [2868, 4367, 1547, 6390],
        [2868,  414, 1547, 6390],
        [2868,  414, 1547, 6390]])
Targets are:
tensor([2868, 4367, 1547, 6390, 2868,  414, 1547, 6390, 2868,  414, 1547, 6390,
        2869,  414, 5198, 6390])
Data is:
tensor([[2869,  414, 5198, 6390],
        [2870,  414, 5198, 6374],
        [6765, 7647, 5198, 6375],
        [6765, 7647, 1548, 6375]])
Targets are:
tensor([2870,  414, 5198,

Data is:
tensor([[3107,  457, 1354, 6444],
        [3107,  458, 1354, 6444],
        [3107,  458, 1354, 6444],
        [3122,  459, 5088, 6444]])
Targets are:
tensor([3107,  458, 1354, 6444, 3107,  458, 1354, 6444, 3122,  459, 5088, 6444,
        3122,  459, 5088, 6444])
Data is:
tensor([[3122,  459, 5088, 6444],
        [6959,  459, 5088, 6445],
        [6959,  459, 5088, 6445],
        [6959,  459, 5088, 6445]])
Targets are:
tensor([6959,  459, 5088, 6445, 6959,  459, 5088, 6445, 6959,  459, 5088, 6445,
        6959,  459, 5089, 6446])
Data is:
tensor([[6959,  459, 5089, 6446],
        [3128,  459, 5089, 6446],
        [3128,  460, 5089, 6446],
        [3128,  460, 5089, 6447]])
Targets are:
tensor([3128,  459, 5089, 6446, 3128,  460, 5089, 6446, 3128,  460, 5089, 6447,
        3128,  461, 5089, 6447])
Data is:
tensor([[3128,  461, 5089, 6447],
        [3128,  461, 1355, 6447],
        [6961,  462, 5090, 6448],
        [6961,  462, 5090, 6448]])
Targets are:
tensor([3128,  461, 1355,

In [44]:
test_mask = generate_square_subsequent_mask(4).to(device)
test_input = torch.tensor([7607, 3156,  255, 1390])

# test_inputtensor([8047, 3156,  255, 1390, 7607, 3156,  256, 1390,   21, 3157,  256, 1392,
#         4092, 3157,  256, 1392])
best_model.eval()
out = best_model(test_input, test_mask)
pred = out.topk(1)[1].view(-1)[-1].item()
print(pred)

5822


#### Sources:

https://pytorch.org/tutorials/beginner/transformer_tutorial.html#define-the-model